const APP_VERSION="7.4.1", STORAGE_KEY="drift-fi078-v5";
const blankState=()=>({version:APP_VERSION,theme:"light",inquiries:[],auditLog:[],backupHistory:[],updatedAt:null});
let state=loadState(), currentView="dashboard", currentInquiryId=null, currentTab="overview", compareSelection=[];

function uid(){return crypto.randomUUID?crypto.randomUUID():Date.now().toString(36)+Math.random().toString(36).slice(2)}
function now(){return new Date().toISOString()}
function esc(v=""){return String(v).replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"}[m]))}
function loadState(){try{return {...blankState(),...JSON.parse(localStorage.getItem(STORAGE_KEY)||"{}")}}catch{return blankState()}}
function saveState(){state.updatedAt=now();localStorage.setItem(STORAGE_KEY,JSON.stringify(state));saveStatus.textContent="Saved locally at "+new Date(state.updatedAt).toLocaleTimeString()}
function setTheme(){document.documentElement.dataset.theme=state.theme==="dark"?"dark":""} setTheme();
function activeInquiries(){return state.inquiries.filter(i=>!i.archived)}
function allEvidence(){return state.inquiries.flatMap(i=>(i.evidence||[]).map(e=>({...e,inquiryId:i.id,inquiryTitle:i.title})))}
function allStations(){return state.inquiries.flatMap(i=>(i.stations||[]).map(s=>({...s,inquiryId:i.id,inquiryTitle:i.title})))}
function getInquiry(){const i=state.inquiries.find(i=>i.id===currentInquiryId);if(i){i.interventionEvents=i.interventionEvents||[];i.relationships=i.relationships||[];}return i}
function stageCounts(i){return {observe:(i.observations||[]).length,diagnose:(i.frictions||[]).length,listen:(i.perspectives||[]).length,predict:(i.forecasts||[]).length,review:(i.reviews||[]).length}}
function health(i){const c=stageCounts(i),vals=Object.values(c).map(v=>Math.min(v,2)/2);return Math.round(vals.reduce((a,b)=>a+b,0)/vals.length*100)}
function metric(label,value){return `<div class="card metric"><div class="label">${label}</div><div class="value">${value}</div></div>`}
function recordLabel(n){return n.title||n.name||n.problem||n.prediction||n.participant||n.inference||n.hypothesis||n.lesson||n.action||"Record"}

function render(){
 document.querySelectorAll(".workspace").forEach(x=>x.classList.remove("active"));
 const id=currentView==="inquiry"?"inquiryWorkspace":currentView+"View";
 document.getElementById(id).classList.add("active");
 document.querySelectorAll(".nav button").forEach(b=>b.classList.toggle("active",b.dataset.view===currentView));
 viewTitle.textContent=currentView==="inquiry"?"Inquiry Workspace":currentView[0].toUpperCase()+currentView.slice(1);
 ({dashboard:renderDashboard,inquiries:renderInquiries,fieldwork:renderFieldwork,evidence:renderEvidence,stations:renderStations,patterns:renderPatterns,control:renderControl,search:renderSearch,templates:renderTemplates,reports:renderReports,archive:renderArchive,settings:renderSettings,diagnostics:renderDiagnostics,inquiry:renderInquiry}[currentView])();
}

function inquiryList(list){
 if(!list.length)return `<div class="empty">No inquiries yet. Create one or load the demo.</div>`;
 return `<div class="inquiry-list">${list.map(i=>`<div class="inquiry-card"><div><h4>${esc(i.title)}</h4><p>${esc(i.question)}</p><div class="badges"><span class="badge">${esc(i.subject||"General")}</span><span class="badge">${health(i)}% health</span><span class="badge">${Object.values(stageCounts(i)).reduce((a,b)=>a+b,0)} core records</span></div></div><div class="toolbar"><button class="btn primary" onclick="openInquiry('${i.id}')">Open</button><button class="btn" onclick="editInquiry('${i.id}')">Edit</button></div></div>`).join("")}</div>`;
}
function renderDashboard(){
 const list=activeInquiries(),obs=list.flatMap(i=>i.observations||[]),fr=list.flatMap(i=>i.frictions||[]),stations=allStations();
 const due=stations.filter(s=>s.nextVisit&&new Date(s.nextVisit)<=new Date()).length;
 dashboardView.innerHTML=`<div class="hero"><div class="card"><div class="eyebrow">Inquiry loop</div><h3>Observe change. Find friction. Test causes. Learn deliberately.</h3><p>Drift Foundation Completion unifies field evidence, reasoning chains, relationships, timelines, search, templates, and analysis in one coherent inquiry system.</p><div class="pipeline">${["Observe","Diagnose","Listen","Predict","Review"].map((s,i)=>`<div class="stage"><strong>${s}</strong><span>${["Collect evidence","Find obstacles","Preserve perspectives","Record expectations","Carry lessons"][i]}</span></div>`).join("")}</div></div><div class="card"><div class="eyebrow">Attention</div><h3>Field readiness</h3><div class="notice">${due?`${due} station visit${due>1?"s are":" is"} due.`:"No station visits are overdue."}</div><div class="notice" style="margin-top:12px">${fr.filter(f=>Number(f.priority)>=50).length} high-priority friction records need attention.</div></div></div>
 <div class="grid cards">${metric("Active inquiries",list.length)}${metric("Evidence items",allEvidence().length)}${metric("Observation stations",stations.length)}${metric("Root cause analyses",list.flatMap(i=>i.rootCauses||[]).length)}</div><div class="card" style="margin-top:18px"><div class="section-head" style="margin:0"><div><div class="eyebrow">Portfolio assurance</div><h3>Quality and closeout control</h3><p class="status">Inspect broken links, orphan evidence, overdue work, and verification readiness across every inquiry.</p></div><button class="btn primary" onclick="currentView='control';render()">Open Control Center</button></div></div>
 <div class="section-head"><h3>Recent inquiries</h3><button class="btn primary" onclick="openInquiryDialog()">New Inquiry</button></div>${inquiryList(list.slice(0,6))}`;
}
function renderInquiries(){inquiriesView.innerHTML=`<div class="section-head"><div><h3>Inquiries</h3><p class="status">Containers for evidence, observations, friction, causes, perspectives, forecasts, and reviews.</p></div><button class="btn primary" onclick="openInquiryDialog()">New Inquiry</button></div>${inquiryList(activeInquiries())}`}
function renderFieldwork(){
 const list=activeInquiries(), due=allStations().filter(s=>s.nextVisit&&new Date(s.nextVisit)<=new Date());
 fieldworkView.innerHTML=`<div class="field-console"><div class="card"><div class="eyebrow">Mobile field console</div><h3>Capture without breaking attention</h3><p class="status">Choose an inquiry, optionally capture your current coordinates, then create the needed field record.</p><label>Active inquiry<select id="fieldInquiry">${list.map(i=>`<option value="${i.id}">${esc(i.title)}</option>`).join("")}</select></label><div class="toolbar" style="margin-top:12px"><button class="btn field-big" onclick="captureLocation()">Capture GPS</button><button class="btn" onclick="startVoiceNote()">Voice note</button></div><div id="fieldLocation" class="location-readout" style="margin-top:10px">Location not captured.</div><div class="capture-grid" style="margin-top:16px"><button class="capture-tile" onclick="fieldCapture()"><strong>Observation</strong><span>Condition, measurement, photo, checklist, and station.</span></button><button class="capture-tile" onclick="fieldEvidence()"><strong>Evidence</strong><span>Photo, note, source, document, measurement, or reference.</span></button><button class="capture-tile" onclick="fieldQuick('friction')"><strong>Friction</strong><span>Record an obstacle or workaround as it happens.</span></button><button class="capture-tile" onclick="fieldQuick('listen')"><strong>Perspective</strong><span>Capture a person or group's interpretation.</span></button><button class="capture-tile" onclick="fieldQuick('change')"><strong>Change</strong><span>Classify a difference from a prior visit.</span></button><button class="capture-tile" onclick="fieldQuick('action')"><strong>Follow-up</strong><span>Create an owned action before leaving the site.</span></button></div></div><div class="card"><div class="eyebrow">Station route</div><h3>${due.length} due</h3>${due.length?due.slice(0,8).map(s=>`<div class="item"><strong>${esc(s.name)}</strong><p>${esc(s.location||s.inquiryTitle)}</p><div class="toolbar"><button class="btn small primary" onclick="visitStation('${s.inquiryId}','${s.id}')">Visit</button>${s.latitude&&s.longitude?`<button class="btn small" onclick="openMap('${s.latitude}','${s.longitude}')">Map</button>`:''}<button class="btn small" onclick="printStationCard('${s.inquiryId}','${s.id}')">Station card</button></div></div>`).join(''):'<div class="empty">No station visits are due.</div>'}</div></div>`;
}

function renderEvidence(){
 const ev=allEvidence();
 evidenceView.innerHTML=`<div class="section-head"><div><h3>Evidence Library</h3><p class="status">Reusable evidence with stable IDs and inquiry relationships.</p></div></div>${ev.length?`<div class="item-list">${ev.map(e=>`<div class="item"><div class="item-top"><div>${e.dataUrl?`<img class="thumb" src="${e.dataUrl}" alt="">`:""}<h5>${esc(e.title)}</h5><p>${esc(e.notes||e.url||"")}</p></div><span class="badge">${esc(e.type)}</span></div><div class="item-meta"><span class="badge">${esc(e.inquiryTitle)}</span><span class="badge">ID ${esc(e.id.slice(0,8))}</span>${e.tags?`<span class="badge">${esc(e.tags)}</span>`:""}</div></div>`).join("")}</div>`:`<div class="empty">No evidence has been added.</div>`}`;
}
function renderStations(){
 const st=allStations();
 stationsView.innerHTML=`<div class="section-head"><div><h3>Observation Stations</h3><p class="status">Repeatable locations, prompts, measurements, and revisit schedules.</p></div></div>${st.length?`<div class="item-list">${st.map(s=>`<div class="item station-card"><div><h5>${esc(s.name)}</h5><p>${esc(s.location||"")}</p><div class="item-meta"><span class="badge">${esc(s.inquiryTitle)}</span><span class="badge">Interval: ${esc(s.interval||"Not set")}</span><span class="badge">Next: ${esc(s.nextVisit||"Not set")}</span></div></div><button class="btn small" onclick="visitStation('${s.inquiryId}','${s.id}')">Record Visit</button></div>`).join("")}</div>`:`<div class="empty">No observation stations have been defined.</div>`}`;
}
function renderPatterns(){
 const fr=activeInquiries().flatMap(i=>i.frictions||[]), changes=activeInquiries().flatMap(i=>i.changes||[]);
 const by=(arr,key)=>Object.entries(arr.reduce((m,x)=>(m[x[key]||"Uncategorized"]=(m[x[key]||"Uncategorized"]||0)+1,m),{})).sort((a,b)=>b[1]-a[1]);
 patternsView.innerHTML=`<div class="grid cards">${metric("Change records",changes.length)}${metric("Friction records",fr.length)}${metric("Root cause factors",activeInquiries().flatMap(i=>i.rootCauses||[]).reduce((n,r)=>n+(r.factors||[]).length,0))}${metric("Evidence links",fr.filter(f=>f.evidenceId).length)}</div><div class="split" style="margin-top:18px"><div class="card"><h3>Change categories</h3>${by(changes,"category").map(([k,v])=>`<div class="item"><strong>${esc(k)}</strong><span style="float:right">${v}</span></div>`).join("")||'<div class="empty">No change patterns yet.</div>'}</div><div class="card"><h3>Friction categories</h3>${by(fr,"category").map(([k,v])=>`<div class="item"><strong>${esc(k)}</strong><span style="float:right">${v}</span></div>`).join("")||'<div class="empty">No friction patterns yet.</div>'}</div></div>`;
}

function recordCollections(i){return {observations:i.observations||[],evidence:i.evidence||[],stations:i.stations||[],changes:i.changes||[],frictions:i.frictions||[],rootCauses:i.rootCauses||[],interventions:i.interventions||[],interventionEvents:i.interventionEvents||[],actions:i.actions||[],stakeholders:i.stakeholders||[],perspectives:i.perspectives||[],forecasts:i.forecasts||[],assumptions:i.assumptions||[],experiments:i.experiments||[],inferences:i.inferences||[],hypotheses:i.hypotheses||[],relationships:i.relationships||[],lessons:i.lessons||[],reviews:i.reviews||[]}}
function allRecordIds(i){return new Set(Object.entries(recordCollections(i)).filter(([k])=>k!=="relationships").flatMap(([,arr])=>arr.map(x=>x.id).filter(Boolean)))}
function integrityScan(i){
 const ids=allRecordIds(i), rel=i.relationships||[], broken=rel.filter(r=>!ids.has(r.fromId)||!ids.has(r.toId));
 const duplicateIds=[];const seen=new Set();Object.values(recordCollections(i)).flat().forEach(r=>{if(!r.id)return;if(seen.has(r.id))duplicateIds.push(r.id);seen.add(r.id)});
 const orphanEvidence=(i.evidence||[]).filter(e=>!rel.some(r=>r.fromId===e.id||r.toId===e.id)&&!(i.frictions||[]).some(f=>f.evidenceId===e.id)&&!(i.rootCauses||[]).some(c=>c.evidenceId===e.id));
 const overdue=(i.actions||[]).filter(a=>a.status!=="Done"&&a.dueDate&&new Date(a.dueDate)<new Date());
 const unresolvedForecasts=(i.forecasts||[]).filter(f=>!f.resolvedDate&&f.status!=="Resolved"&&f.targetDate&&new Date(f.targetDate)<new Date());
 return {broken,duplicateIds:[...new Set(duplicateIds)],orphanEvidence,overdue,unresolvedForecasts};
}
function verificationReadiness(i){
 const ints=i.interventions||[],events=i.interventionEvents||[],reviews=i.reviews||[],lessons=i.lessons||[];
 const completed=ints.filter(x=>["Completed","Verified"].includes(x.status)).length;
 const verifiedIds=new Set(events.filter(x=>x.eventType==="Verification"||x.status==="Verified").map(x=>x.interventionId).filter(Boolean));
 const checks=[
  {label:"Inquiry baseline is defined",ok:!!i.baseline},
  {label:"Desired outcome is defined",ok:!!i.outcome},
  {label:"At least one evidence record exists",ok:(i.evidence||[]).length>0},
  {label:"High-priority friction has an owner",ok:(i.frictions||[]).filter(f=>Number(f.priority)>=20).every(f=>!!f.owner)},
  {label:"Completed interventions have verification",ok:completed===0||ints.filter(x=>["Completed","Verified"].includes(x.status)).every(x=>verifiedIds.has(x.id))},
  {label:"No overdue open actions",ok:integrityScan(i).overdue.length===0},
  {label:"Outcome review is recorded",ok:reviews.length>0},
  {label:"At least one lesson is captured",ok:lessons.length>0}
 ];
 return {checks,score:Math.round(checks.filter(x=>x.ok).length/checks.length*100),verified:verifiedIds.size,completed};
}
function renderVerification(i){
 const r=verificationReadiness(i),scan=integrityScan(i),events=i.interventionEvents||[];
 const verificationEvents=events.filter(x=>x.eventType==="Verification"||x.status==="Verified");
 return `<div class="control-grid"><div class="card closeout-card"><div class="eyebrow">Closeout readiness</div><div class="readiness-ring" style="--pct:${r.score}"><strong>${r.score}%</strong></div><p class="status" style="text-align:center">Evidence-backed readiness to close or baseline this inquiry.</p></div><div class="card"><h3>Verification status</h3>${metric("Completed interventions",r.completed)}${metric("Verified interventions",r.verified)}</div><div class="card"><h3>Integrity alerts</h3><div class="badges"><span class="badge">${scan.broken.length} broken links</span><span class="badge">${scan.orphanEvidence.length} orphan evidence</span><span class="badge">${scan.overdue.length} overdue actions</span><span class="badge">${scan.unresolvedForecasts.length} overdue forecasts</span></div></div></div><div class="split" style="margin-top:18px"><div class="card"><h3>Closeout checklist</h3><div class="checklist">${r.checks.map(x=>`<div class="check-row"><span class="check-icon ${x.ok?'ok':'warn'}">${x.ok?'✓':'!'}</span><span>${esc(x.label)}</span><strong>${x.ok?'Ready':'Open'}</strong></div>`).join('')}</div></div><div class="card"><div class="section-head" style="margin:0 0 12px"><div><h3>Verification register</h3><p class="status">Measured confirmation that an intervention produced the intended result.</p></div><button class="btn primary" onclick="openRecordDialog('interventionEvent')">Add Verification</button></div>${verificationEvents.length?verificationEvents.map(x=>`<div class="history-line verification"><strong>${esc(x.title||'Verification')}</strong><p>${esc(x.metric||x.notes||'')}</p><div class="item-meta"><span class="badge">${esc(x.eventDate||'')}</span>${x.interventionId?`<span class="badge">Intervention ${esc(x.interventionId.slice(0,8))}</span>`:''}${x.evidenceId?`<span class="badge">Evidence ${esc(x.evidenceId.slice(0,8))}</span>`:''}</div></div>`).join(''):'<div class="empty">No verification entries yet.</div>'}</div></div>`;
}
function renderControl(){
 const list=activeInquiries();const scans=list.map(i=>({i,scan:integrityScan(i),ready:verificationReadiness(i)}));
 const broken=scans.reduce((n,x)=>n+x.scan.broken.length,0),orphans=scans.reduce((n,x)=>n+x.scan.orphanEvidence.length,0),overdue=scans.reduce((n,x)=>n+x.scan.overdue.length,0),avg=list.length?Math.round(scans.reduce((n,x)=>n+x.ready.score,0)/list.length):0;
 controlView.innerHTML=`<div class="section-head"><div><h3>Control Center</h3><p class="status">Portfolio-wide quality, traceability, verification, and closeout readiness.</p></div></div><div class="grid cards">${metric("Average readiness",avg+"%")} ${metric("Broken relationships",broken)} ${metric("Orphan evidence",orphans)} ${metric("Overdue actions",overdue)}</div><div class="card" style="margin-top:18px"><h3>Inquiry assurance register</h3><div style="overflow:auto"><table class="trace-table"><thead><tr><th>Inquiry</th><th>Readiness</th><th>Health</th><th>Broken links</th><th>Orphan evidence</th><th>Overdue work</th><th></th></tr></thead><tbody>${scans.map(x=>`<tr><td><strong>${esc(x.i.title)}</strong></td><td>${x.ready.score}%</td><td>${health(x.i)}%</td><td>${x.scan.broken.length}</td><td>${x.scan.orphanEvidence.length}</td><td>${x.scan.overdue.length+x.scan.unresolvedForecasts.length}</td><td><button class="btn small" onclick="openInquiryVerification('${x.i.id}')">Inspect</button></td></tr>`).join('')}</tbody></table></div></div>`;
}
function openInquiryVerification(id){currentInquiryId=id;currentView="inquiry";currentTab="verification";render()}
function archiveManifest(i){const cols=recordCollections(i);return {records:Object.entries(cols).filter(([k])=>k!=="relationships").reduce((n,[,a])=>n+a.length,0),relationships:(i.relationships||[]).length,evidence:(i.evidence||[]).length,lessons:(i.lessons||[]).length}}

function searchableRecords(){
 const types={observations:"Observation",evidence:"Evidence",stations:"Station",changes:"Change",frictions:"Friction",rootCauses:"Root Cause",interventions:"Intervention",interventionEvents:"Intervention History",actions:"Action",stakeholders:"Stakeholder",interviewGuides:"Interview Guide",perspectives:"Perspective",themes:"Theme",forecasts:"Forecast",assumptions:"Assumption",experiments:"Experiment",inferences:"Inference",hypotheses:"Hypothesis",lessons:"Lesson"};
 return state.inquiries.flatMap(i=>Object.entries(types).flatMap(([key,label])=>(i[key]||[]).map(r=>({inquiryId:i.id,inquiryTitle:i.title,type:label,record:r,text:JSON.stringify(r).toLowerCase()}))));
}
function renderSearch(){
 const recent=searchableRecords().sort((a,b)=>String(b.record.updatedAt||b.record.createdAt||'').localeCompare(String(a.record.updatedAt||a.record.createdAt||''))).slice(0,12);
 searchView.innerHTML=`<div class="card"><div class="eyebrow">Global index</div><h3>Search and smart collections</h3><div class="searchbox"><input id="globalSearch" placeholder="Search observations, evidence, causes, people, predictions, lessons…"><button class="btn primary" onclick="runSearch()">Search</button></div><div class="filter-pills"><button onclick="applySmartSearch('status:open')">Open work</button><button onclick="applySmartSearch('type:Evidence')">Evidence</button><button onclick="applySmartSearch('type:Friction')">Friction</button><button onclick="applySmartSearch('type:Lesson')">Lessons</button><button onclick="applySmartSearch('confidence:low')">Low confidence</button><button onclick="saveCurrentSearch()">Save search</button></div><div id="savedSearches" class="toolbar" style="margin-top:10px"></div><div id="searchResults" class="item-list" style="margin-top:14px">${recent.map(searchResultCard).join('')||'<div class="empty">No indexed records.</div>'}</div></div>`;renderSavedSearches();
}
function searchResultCard(x){return `<div class="item"><div class="item-top"><div><h5>${esc(x.record.title||x.record.name||x.record.problem||x.record.prediction||x.record.participant||x.type)}</h5><p>${esc(x.record.notes||x.record.description||x.record.perspective||x.record.conclusion||x.record.outcome||x.record.hypothesis||x.record.inference||"")}</p></div><span class="badge">${x.type}</span></div><div class="item-meta"><span class="badge">${esc(x.inquiryTitle)}</span>${x.record.status?`<span class="badge">${esc(x.record.status)}</span>`:''}</div><button class="btn small" onclick="openInquiry('${x.inquiryId}')">Open inquiry</button></div>`}
function runSearch(){const raw=(globalSearch.value||"").trim(),tokens=raw.split(/\s+/).filter(Boolean),rows=searchableRecords().filter(x=>tokens.every(t=>{const [k,...rest]=t.split(':'),v=rest.join(':').toLowerCase();if(rest.length&&k==='type')return x.type.toLowerCase().includes(v);if(rest.length&&k==='status')return String(x.record.status||'open').toLowerCase().includes(v);if(rest.length&&k==='confidence'&&v==='low')return Number(x.record.confidence||100)<50;return x.text.includes(t.toLowerCase())||x.inquiryTitle.toLowerCase().includes(t.toLowerCase())}));searchResults.innerHTML=rows.length?rows.slice(0,150).map(searchResultCard).join(""):`<div class="empty">No matching records.</div>`}
function applySmartSearch(q){globalSearch.value=q;runSearch()}
function saveCurrentSearch(){const q=(globalSearch.value||'').trim();if(!q)return alert('Enter a search first.');state.savedSearches=state.savedSearches||[];if(!state.savedSearches.includes(q))state.savedSearches.push(q);saveState();renderSavedSearches()}
function renderSavedSearches(){if(!window.savedSearches)return;const arr=state.savedSearches||[];savedSearches.innerHTML=arr.map((q,n)=>`<button class="btn small" onclick="applySmartSearch('${esc(q)}')">${esc(q)}</button><button class="btn small danger" onclick="removeSavedSearch(${n})">×</button>`).join('')}
function removeSavedSearch(n){state.savedSearches.splice(n,1);saveState();renderSavedSearches()}

function renderTemplates(){templatesView.innerHTML=`<div class="section-head"><div><h3>Inquiry Templates</h3><p class="status">Start with a rigorous frame, then adapt it.</p></div></div><div class="template-grid">${templateCatalog.map((t,n)=>`<div class="template-card"><div class="eyebrow">Template</div><h3>${t.name}</h3><p class="status">${t.question}</p><button class="btn primary" onclick="createFromTemplate(${n})">Use Template</button></div>`).join("")}</div>`}
function createFromTemplate(n){const t=templateCatalog[n],id=uid();state.inquiries.push({id,title:t.name,subject:t.subject,question:t.question,baseline:t.baseline,outcome:t.outcome,location:"",owner:"",createdAt:now(),updatedAt:now(),archived:false,observations:[],evidence:[],stations:[],changes:[],frictions:[],rootCauses:[],interventionEvents:[],interventions:[],actions:[],stakeholders:[],interviewGuides:[],perspectives:[],themes:[],forecasts:[],assumptions:[],experiments:[],inferences:[],hypotheses:[],relationships:[],lessons:[],reviews:[]});saveState();openInquiry(id)}
function renderReports(){
 const cards=[
  ["Inquiry Narrative","narrative"],["Evidence Register","evidence"],["Change Timeline","timeline"],["Friction Atlas","friction"],["Reasoning Chain","reasoning"],["Stakeholder & Consensus","stakeholders"],["Calibration Summary","calibration"],["Lessons Compendium","lessons"]
 ];
 reportsView.innerHTML=`<div class="section-head"><div><h3>Report Studio</h3><p class="status">Generate a complete printable report from any inquiry.</p></div></div><div class="grid cards">${cards.map(([name,type])=>`<div class="card"><div class="eyebrow">Report</div><h3>${name}</h3><label>Inquiry<select id="report-${type}">${state.inquiries.map(i=>`<option value="${i.id}">${esc(i.title)}</option>`).join("")}</select></label><button class="btn primary" style="margin-top:12px" onclick="openReport('${type}',document.getElementById('report-${type}').value)">Generate</button></div>`).join("")}</div>`
}
function openReport(type,id){currentInquiryId=id;const i=getInquiry();if(!i)return;const w=window.open("","_blank");const body=buildReport(type,i);w.document.write(`<!doctype html><html><head><meta charset="utf-8"><title>${esc(i.title)} — ${esc(type)}</title><style>body{font-family:Arial,sans-serif;color:#202725;max-width:1000px;margin:40px auto;padding:0 24px;line-height:1.5}h1{font-size:34px}h2{border-top:2px solid #315f59;padding-top:14px;margin-top:30px}.meta{color:#65706c}.item{border:1px solid #d7d1c4;border-radius:10px;padding:12px;margin:10px 0}.badge{display:inline-block;border:1px solid #d7d1c4;border-radius:999px;padding:3px 7px;margin:2px;font-size:12px}@media print{button{display:none}}
.field-console{display:grid;grid-template-columns:1.2fr .8fr;gap:18px}.capture-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:10px}.capture-tile{min-height:116px;border:1px solid var(--line);background:var(--panel2);border-radius:15px;padding:15px;text-align:left;color:var(--text)}.capture-tile strong{display:block;font-size:1rem;margin-bottom:6px}.capture-tile span{font-size:.8rem;color:var(--muted)}.location-readout{font-family:ui-monospace,SFMono-Regular,Menlo,monospace;font-size:.82rem;padding:10px;background:var(--panel2);border-radius:10px}.history-line{border-left:3px solid var(--accent);padding:10px 12px;margin:8px 0;background:var(--panel2);border-radius:0 10px 10px 0}.filter-pills{display:flex;flex-wrap:wrap;gap:7px;margin-top:10px}.filter-pills button{border:1px solid var(--line);background:var(--panel2);color:var(--text);padding:7px 10px;border-radius:999px}.map-link{display:inline-flex;align-items:center;gap:6px}.field-big{font-size:1.05rem;padding:16px}.verification{border-left:4px solid var(--good)}
@media(max-width:900px){.field-console{grid-template-columns:1fr}.capture-grid{grid-template-columns:1fr 1fr}}@media(max-width:560px){.capture-grid{grid-template-columns:1fr}.field-big{width:100%}}
</style></head><body><button onclick="print()">Print / Save PDF</button>${body}</body><\/html>`);w.document.close()}
function reportItems(title,arr,formatter){return `<h2>${title}</h2>${arr.length?arr.map(formatter).join(""):`<p class="meta">No records.</p>`}`}
function buildReport(type,i){const head=`<h1>${esc(i.title)}</h1><p class="meta">${esc(i.question||"")}</p><p><strong>Baseline:</strong> ${esc(i.baseline||"Not defined")}<br><strong>Desired outcome:</strong> ${esc(i.outcome||"Not defined")}</p>`;const item=x=>`<div class="item"><strong>${esc(recordLabel(x))}</strong><p>${esc(x.notes||x.description||x.inference||x.hypothesis||x.lesson||x.perspective||x.actualOutcome||"")}</p></div>`;
 if(type==="evidence")return head+reportItems("Evidence Register",i.evidence||[],item);
 if(type==="timeline")return head+reportItems("Change Timeline",(i.changes||[]).slice().sort((a,b)=>String(a.createdAt).localeCompare(String(b.createdAt))),item);
 if(type==="friction")return head+reportItems("Friction Atlas",(i.frictions||[]).slice().sort((a,b)=>(Number(b.priority)||0)-(Number(a.priority)||0)),x=>`<div class="item"><strong>${esc(x.title)}</strong><span class="badge">Priority ${esc(x.priority||0)}</span><span class="badge">${esc(x.status||"Open")}</span><p>${esc(x.description||"")}</p></div>`);
 if(type==="reasoning")return head+reportItems("Inferences",i.inferences||[],item)+reportItems("Hypotheses",i.hypotheses||[],item)+reportItems("Forecasts",i.forecasts||[],item)+reportItems("Interventions",i.interventions||[],item)+reportItems("Lessons",i.lessons||[],item);
 if(type==="stakeholders")return head+reportItems("Stakeholders",i.stakeholders||[],item)+reportItems("Perspectives",i.perspectives||[],item);
 if(type==="calibration")return head+reportItems("Resolved Forecasts",(i.forecasts||[]).filter(x=>x.status==="Resolved"),x=>`<div class="item"><strong>${esc(x.prediction)}</strong><span class="badge">Confidence ${esc(x.confidence)}%</span><span class="badge">Brier ${forecastBrier(x)?.toFixed(3)??"—"}</span><p>${esc(x.actualOutcome||"")}</p></div>`);
 if(type==="lessons")return head+reportItems("Lessons Compendium",i.lessons||[],item);
 return head+reportItems("Observations",i.observations||[],item)+reportItems("Evidence",i.evidence||[],item)+reportItems("Friction",i.frictions||[],item)+reportItems("Root Causes",i.rootCauses||[],item)+reportItems("Perspectives",i.perspectives||[],item)+reportItems("Forecasts",i.forecasts||[],item)+reportItems("Reviews",i.reviews||[],item)+reportItems("Lessons",i.lessons||[],item)
}
function renderArchive(){const arr=state.inquiries.filter(i=>i.archived);archiveView.innerHTML=`<div class="section-head"><div><h3>Archived inquiries</h3><p class="status">Closed inquiries remain traceable, searchable, and restorable.</p></div></div>${arr.length?`<div class="item-list">${arr.map(i=>{const m=archiveManifest(i),r=verificationReadiness(i);return `<div class="card"><div class="item-top"><div><div class="eyebrow">Archived inquiry</div><h3>${esc(i.title)}</h3><p>${esc(i.question)}</p></div><div class="toolbar"><button class="btn" onclick="openInquiry('${i.id}')">Open</button><button class="btn primary" onclick="toggleArchive('${i.id}')">Restore</button></div></div><div class="archive-summary" style="margin-top:14px"><div><strong>${m.records}</strong><span class="status">Records</span></div><div><strong>${m.relationships}</strong><span class="status">Relationships</span></div><div><strong>${m.evidence}</strong><span class="status">Evidence</span></div><div><strong>${r.score}%</strong><span class="status">Closeout readiness</span></div></div></div>`}).join('')}</div>`:`<div class="empty">No archived inquiries.</div>`}` }
function renderSettings(){
 const bytes=new Blob([JSON.stringify(state)]).size,mb=(bytes/1048576).toFixed(2),last=(state.backupHistory||[]).slice(-1)[0];
 settingsView.innerHTML=`<div class="split"><div class="card"><div class="eyebrow">Local-first</div><h3>Storage and backup integrity</h3><p class="status">All data is stored in this browser. Create verified backups regularly.</p><div class="backup-box"><strong>${mb} MB</strong><br><span class="status">Current serialized data size</span></div><div class="toolbar" style="margin-top:14px"><button class="btn primary" onclick="exportVerifiedBackup()">Verified Backup</button><button class="btn" onclick="exportBtn.click()">Plain JSON</button><button class="btn danger" onclick="clearAllData()">Clear All Data</button></div><p class="status">Last verified backup: ${last?esc(new Date(last.date).toLocaleString()):'None recorded'}</p></div><div class="card"><div class="eyebrow">Auditability</div><h3>Recent system activity</h3>${renderAuditLog(12)}</div></div>`}

function openInquiry(id){currentInquiryId=id;currentView="inquiry";currentTab="overview";render()}
function setTab(t){currentTab=t;renderInquiry()}
function renderInquiry(){
 const i=getInquiry();if(!i){currentView="inquiries";return render()}
 const tabs=[["overview","Overview"],["reasoning","Reasoning"],["timeline","Timeline"],["graph","Graph"],["observe","Observe"],["evidence","Evidence"],["stations","Stations"],["compare","Compare"],["changes","Changes"],["diagnose","Diagnose"],["causes","Root Causes"],["interventions","Interventions"],["actions","Actions"],["backlog","Backlog"],["governance","Governance"],["verification","Verification"],["stakeholders","Stakeholders"],["guides","Interview Guides"],["listen","Perspectives"],["coding","Themes"],["consensus","Consensus"],["predict","Predictions"],["assumptions","Assumptions"],["calibration","Calibration"],["experiments","Experiments"],["review","Review"]];
 inquiryWorkspace.innerHTML=`<div class="inquiry-header"><div><div class="eyebrow">${esc(i.subject||"Inquiry")}</div><h2>${esc(i.title)}</h2><p>${esc(i.question)}</p></div><div class="toolbar"><button class="btn" onclick="window.print()">Print / Save PDF</button><button class="btn" onclick="toggleArchive('${i.id}')">${i.archived?"Restore":"Archive"}</button></div></div><div class="card" style="margin-bottom:14px"><div style="display:flex;justify-content:space-between"><strong>Inquiry health</strong><span>${health(i)}%</span></div><div class="health" style="margin-top:8px"><span style="width:${health(i)}%"></span></div></div><div class="tabs">${tabs.map(([k,n])=>`<button class="${currentTab===k?"active":""}" onclick="setTab('${k}')">${n}</button>`).join("")}</div><div class="tab-panel active">${renderInquiryTab(currentTab,i)}</div>`;
}
function renderOverview(i){
 const counts={
  observations:(i.observations||[]).length,
  evidence:(i.evidence||[]).length,
  friction:(i.frictions||[]).length,
  causes:(i.rootCauses||[]).length,
  interventions:(i.interventions||[]).length,
  actions:(i.actions||[]).length,
  perspectives:(i.perspectives||[]).length,
  forecasts:(i.forecasts||[]).length,
  reviews:(i.reviews||[]).length,
  lessons:(i.lessons||[]).length
 };
 const recent=all(i).filter(x=>x.record&&x.record.id).sort((a,b)=>String(b.record.updatedAt||b.record.createdAt||'').localeCompare(String(a.record.updatedAt||a.record.createdAt||''))).slice(0,6);
 const openActions=(i.actions||[]).filter(x=>!['Done','Closed','Complete','Completed'].includes(x.status)).length;
 const overdueForecasts=(i.forecasts||[]).filter(x=>x.targetDate&&new Date(x.targetDate)<new Date()&&!['Resolved','Cancelled'].includes(x.status)).length;
 return `<div class="grid cards">${metric('Observations',counts.observations)}${metric('Evidence',counts.evidence)}${metric('Friction',counts.friction)}${metric('Interventions',counts.interventions)}</div>
 <div class="split" style="margin-top:18px"><div class="card"><div class="eyebrow">Inquiry frame</div><h3>${esc(i.title)}</h3><p><strong>Guiding question</strong><br>${esc(i.question||'Not defined')}</p><p><strong>Baseline</strong><br>${esc(i.baseline||'Not defined')}</p><p><strong>Desired outcome</strong><br>${esc(i.outcome||'Not defined')}</p><div class="badges"><span class="badge">${esc(i.owner||'No owner')}</span><span class="badge">${esc(i.location||'No location')}</span></div></div>
 <div class="card"><div class="eyebrow">Attention</div><h3>What needs work</h3><div class="notice">${openActions} open action${openActions===1?'':'s'}.</div><div class="notice" style="margin-top:10px">${overdueForecasts} overdue forecast${overdueForecasts===1?'':'s'} awaiting resolution.</div><div class="progress-list" style="margin-top:14px">${Object.entries(counts).map(([k,v])=>`<div class="progress-row"><span>${esc(k)}</span><div class="bar"><span style="width:${Math.min(v,5)*20}%"></span></div><strong>${v}</strong></div>`).join('')}</div></div></div>
 <div class="card" style="margin-top:18px"><div class="section-head" style="margin:0 0 12px"><div><h3>Recent inquiry activity</h3><p class="status">The most recently created or updated records.</p></div></div>${recent.length?`<div class="item-list">${recent.map(x=>`<button class="item record-open-button" onclick="openRecordInspector('${i.id}','${x.type}','${x.record.id}')"><span class="badge">${esc(x.type)}</span><strong>${esc(recordLabel(x.record))}</strong><span class="status">${esc(new Date(x.record.updatedAt||x.record.createdAt).toLocaleString())}</span></button>`).join('')}</div>`:'<div class="empty">No inquiry records have been created yet.</div>'}</div>`;
}

function renderInquiryTab(t,i){
 if(t==="overview")return renderOverview(i);
 if(t==="reasoning")return renderReasoning(i);
 if(t==="timeline")return renderTimeline(i);
 if(t==="graph")return renderGraph(i);
 if(t==="observe")return genericTab("What changed?","Record visits and field observations.","observe",i.observations||[]);
 if(t==="evidence")return genericTab("Evidence Engine","Create reusable notes, photos, documents, URLs, measurements, and audio references.","evidence",i.evidence||[]);
 if(t==="stations")return genericTab("Observation Stations","Define repeatable places, prompts, required measurements, and revisit intervals.","station",i.stations||[]);
 if(t==="compare")return renderCompare(i);
 if(t==="changes")return genericTab("Change Detection","Classify and explain differences between observations.","change",i.changes||[]);
 if(t==="diagnose")return renderFriction(i);
 if(t==="causes")return renderCauses(i);
 if(t==="interventions")return renderInterventions(i);
 if(t==="actions")return renderActions(i);
 if(t==="backlog")return renderBacklog(i);
 if(t==="governance")return renderGovernance(i);
 if(t==="verification")return renderVerification(i);
 if(t==="stakeholders")return renderStakeholders(i);
 if(t==="guides")return renderGuides(i);
 if(t==="listen")return renderPerspectives(i);
 if(t==="coding")return renderCoding(i);
 if(t==="consensus")return renderConsensus(i);
 if(t==="predict")return renderForecasts(i);
 if(t==="assumptions")return renderAssumptions(i);
 if(t==="calibration")return renderCalibration(i);
 if(t==="experiments")return renderExperiments(i);
 return genericTab("What happened and what did we learn?","Capture outcomes, explanations, and lessons.","review",i.reviews||[]);
}
function renderReasoning(i){
 const inf=i.inferences||[],hyp=i.hypotheses||[],fore=i.forecasts||[],ints=i.interventions||[],reviews=i.reviews||[],less=i.lessons||[];
 return `<div class="card"><div class="section-head" style="margin:0 0 12px"><div><h3>Reasoning Chain</h3><p class="status">Keep observation, inference, explanation, expectation, action, outcome, and lesson distinct.</p></div><div class="toolbar"><button class="btn" onclick="openRecordDialog('inference')">Add Inference</button><button class="btn" onclick="openRecordDialog('hypothesis')">Add Hypothesis</button><button class="btn primary" onclick="openRecordDialog('lesson')">Add Lesson</button></div></div><div class="reason-chain">${[["Observations",(i.observations||[]).length],["Evidence",(i.evidence||[]).length],["Inferences",inf.length],["Hypotheses",hyp.length],["Predictions",fore.length],["Interventions",ints.length],["Reviews",reviews.length],["Lessons",less.length]].map((x,n)=>`${n?'<div class="reason-arrow">→</div>':''}<div class="reason-node"><div class="eyebrow">${x[0]}</div><h3>${x[1]}</h3></div>`).join("")}</div></div><div class="split" style="margin-top:18px"><div class="card"><h3>Inferences</h3>${renderRecords("inference",inf)}</div><div class="card"><h3>Hypotheses</h3>${renderRecords("hypothesis",hyp)}</div></div><div class="card" style="margin-top:18px"><h3>Lessons</h3>${renderRecords("lesson",less)}</div>`;
}
function entityTimeline(i){const map={observations:"Observation",evidence:"Evidence",changes:"Change",frictions:"Friction",rootCauses:"Root Cause",interventions:"Intervention",interventionEvents:"Intervention History",actions:"Action",perspectives:"Perspective",forecasts:"Forecast",experiments:"Experiment",inferences:"Inference",hypotheses:"Hypothesis",lessons:"Lesson",reviews:"Review"};return Object.entries(map).flatMap(([k,type])=>(i[k]||[]).map(r=>({type,date:r.observedAt||r.discovered||r.startDate||r.targetDate||r.resolvedDate||r.createdAt||"",title:r.title||r.problem||r.prediction||r.participant||type,body:r.notes||r.description||r.conclusion||r.perspective||r.outcome||r.inference||r.hypothesis||r.lesson||""}))).sort((a,b)=>String(a.date).localeCompare(String(b.date)))}
function renderTimeline(i){const rows=entityTimeline(i);return `<div class="card"><div class="section-head" style="margin:0 0 12px"><div><h3>Inquiry Timeline</h3><p class="status">A single chronological view across fieldwork, reasoning, action, and learning.</p></div></div>${rows.length?`<div class="timeline">${rows.map(r=>`<div class="timeline-event"><div class="eyebrow">${esc(r.type)} · ${esc(String(r.date).slice(0,10)||"Undated")}</div><h4 style="margin:.3rem 0">${esc(r.title)}</h4><p class="status">${esc(r.body)}</p></div>`).join("")}</div>`:`<div class="empty">No timeline records yet.</div>`}</div>`}
function renderGraph(i){
 const nodes=[...(i.observations||[]),...(i.evidence||[]),...(i.frictions||[]),...(i.rootCauses||[]),...(i.inferences||[]),...(i.hypotheses||[]),...(i.forecasts||[]),...(i.interventions||[]),...(i.lessons||[])], rel=i.relationships||[], byId=Object.fromEntries(nodes.map(n=>[n.id,n]));
 const invalid=rel.filter(r=>!byId[r.fromId]||!byId[r.toId]).length;
 return `<div class="grid cards">${metric("Graph nodes",nodes.length)}${metric("Relationships",rel.length)}${metric("Orphan nodes",nodes.filter(n=>!rel.some(r=>r.fromId===n.id||r.toId===n.id)).length)}${metric("Broken links",invalid)}</div><div class="card" style="margin-top:18px"><div class="section-head" style="margin:0 0 12px"><div><h3>Relationship Graph</h3><p class="status">Connect evidence, reasoning, decisions, and outcomes. Record labels replace opaque IDs.</p></div><button class="btn primary" onclick="openRecordDialog('relationship')">Add Relationship</button></div><div class="graph">${nodes.map(n=>{const links=rel.filter(r=>r.fromId===n.id||r.toId===n.id).length;return `<div class="graph-node"><div class="node-id">${esc(n.id)}</div><strong>${esc(recordLabel(n))}</strong><div class="links">${links} relationship${links===1?"":"s"}</div></div>`}).join("")||'<div class="empty">No graph nodes yet.</div>'}</div><div class="item-list" style="margin-top:16px">${rel.map(r=>`<div class="relationship-row item ${(!byId[r.fromId]||!byId[r.toId])?"invalid-link":""}"><div><strong>${esc(byId[r.fromId]?recordLabel(byId[r.fromId]):"Missing record")}</strong><div class="node-id">${esc(r.fromId)}</div></div><div class="arrow">${esc(r.relation||"→")}</div><div><strong>${esc(byId[r.toId]?recordLabel(byId[r.toId]):"Missing record")}</strong><div class="node-id">${esc(r.toId)}</div></div></div>`).join("")}</div></div>`
}
function renderForecasts(i){
 const arr=i.forecasts||[],resolved=arr.filter(f=>f.status==="Resolved"),open=arr.filter(f=>f.status!=="Resolved");
 return `<div class="grid cards">${metric("Open forecasts",open.length)}${metric("Resolved",resolved.length)}${metric("Average confidence",arr.length?Math.round(arr.reduce((n,f)=>n+(Number(f.confidence)||0),0)/arr.length)+"%":"—")}${metric("Awaiting outcome",open.filter(f=>f.targetDate&&new Date(f.targetDate)<=new Date()).length)}</div><div class="card" style="margin-top:18px"><div class="section-head" style="margin:0 0 12px"><div><h3>Prediction Registry</h3><p class="status">Record forecasts before outcomes are known, then resolve them without rewriting the original prediction.</p></div><button class="btn primary" onclick="openRecordDialog('predict')">Add Prediction</button></div>${arr.length?`<div class="item-list">${arr.map(f=>{const b=forecastBrier(f);return `<div class="item"><div class="item-top"><div><h5>${esc(f.prediction)}</h5><p>${esc(f.indicators||"")}</p></div><div class="toolbar">${f.status!=="Resolved"?`<button class="btn small primary" onclick="resolveForecast('${f.id}')">Resolve</button>`:""}<button class="btn small danger" onclick="deleteRecord('predict','${f.id}')">Delete</button></div></div><div class="item-meta"><span class="badge">Confidence: ${esc(f.confidence||"0")}%</span><span class="badge">Target: ${esc(f.targetDate||"None")}</span><span class="badge">Status: ${esc(f.status||"Open")}</span>${f.forecastType?`<span class="badge">${esc(f.forecastType)}</span>`:""}${b!==null?`<span class="badge">Brier: ${b.toFixed(3)}</span>`:""}</div>${f.actualOutcome?`<div class="notice" style="margin-top:10px"><strong>Outcome:</strong> ${esc(f.actualOutcome)}</div>`:""}</div>`}).join("")}</div>`:`<div class="empty">No predictions yet.</div>`}</div>`;
}
function resolveForecast(id){
 const i=getInquiry(),f=(i.forecasts||[]).find(x=>x.id===id);if(!f)return;
 const happened=prompt("Did the predicted event occur? Enter 1 for yes or 0 for no.",f.outcomeBinary??"");
 if(happened===null)return;if(!["0","1"].includes(happened.trim())){alert("Enter 1 or 0.");return}
 const outcome=prompt("Describe the actual outcome.",f.actualOutcome||"");if(outcome===null)return;
 f.outcomeBinary=happened.trim();f.actualOutcome=outcome;f.resolvedDate=new Date().toISOString().slice(0,10);f.status="Resolved";saveState();renderInquiry();
}
function renderAssumptions(i){
 const arr=i.assumptions||[];
 return `<div class="grid cards">${metric("Assumptions",arr.length)}${metric("Validated",arr.filter(a=>a.status==="True").length)}${metric("Failed",arr.filter(a=>a.status==="False").length)}${metric("Unknown",arr.filter(a=>!a.status||a.status==="Unknown").length)}</div><div class="card" style="margin-top:18px"><div class="section-head" style="margin:0 0 12px"><div><h3>Assumption Tracker</h3><p class="status">Treat assumptions as reusable claims that can be tested, linked, and revisited.</p></div><button class="btn primary" onclick="openRecordDialog('assumption')">Add Assumption</button></div>${renderRecords("assumption",arr)}</div>`;
}
function renderCalibration(i){
 const arr=(i.forecasts||[]).filter(f=>f.status==="Resolved"&&forecastBrier(f)!==null),avg=arr.length?arr.reduce((n,f)=>n+forecastBrier(f),0)/arr.length:null;
 const bands=[[0,20],[21,40],[41,60],[61,80],[81,100]].map(([lo,hi])=>{const fs=arr.filter(f=>Number(f.confidence)>=lo&&Number(f.confidence)<=hi),pred=fs.length?Math.round(fs.reduce((n,f)=>n+Number(f.confidence),0)/fs.length):null,acc=fs.length?Math.round(fs.reduce((n,f)=>n+Number(f.outcomeBinary),0)/fs.length*100):null;return{label:`${lo}–${hi}`,count:fs.length,pred,acc}});
 const domains=Object.entries(arr.reduce((m,f)=>{const d=f.domain||f.forecastType||"General";(m[d]??=[]).push(f);return m},{}));
 return `<div class="grid cards">${metric("Resolved forecasts",arr.length)}${metric("Mean Brier",avg===null?"—":avg.toFixed(3))}${metric("Accuracy",arr.length?Math.round(arr.reduce((n,f)=>n+Number(f.outcomeBinary),0)/arr.length*100)+"%":"—")}${metric("Status",avg===null?"No data":avg<.1?"Strong":avg<.25?"Developing":"Needs work")}</div><div class="split" style="margin-top:18px"><div class="card"><h3>Reliability curve</h3><div class="chart">${bands.map(b=>`<div class="chart-col" title="${b.count} forecasts; predicted ${b.pred??0}%; actual ${b.acc??0}%"><div class="chart-bar" style="height:${b.acc??0}%"></div><small>${b.label}%</small></div>`).join("")}</div><div class="axis-note">Bar height is actual success rate. Compare it with each confidence band.</div></div><div class="card"><h3>Calibration by domain</h3>${domains.length?domains.map(([d,fs])=>{const score=fs.reduce((n,f)=>n+forecastBrier(f),0)/fs.length;return `<div class="item"><strong>${esc(d)}</strong><div class="item-meta"><span class="badge">${fs.length} forecasts</span><span class="badge">Brier ${score.toFixed(3)}</span></div></div>`}).join(""):'<div class="empty">Add forecast domains or types.</div>'}</div></div><div class="card" style="margin-top:18px"><h3>Forecast reflection queue</h3>${arr.length?arr.slice().sort((a,b)=>forecastBrier(b)-forecastBrier(a)).map(f=>`<div class="item"><strong>${esc(f.prediction)}</strong><div class="item-meta"><span class="badge">${esc(f.confidence)}% confidence</span><span class="badge">Outcome ${f.outcomeBinary==='1'?'occurred':'did not occur'}</span><span class="badge">Brier ${forecastBrier(f).toFixed(3)}</span></div><p>${esc(f.actualOutcome||"")}</p></div>`).join(""):'<div class="empty">Resolve predictions to populate analytics.</div>'}</div>`
}
function renderExperiments(i){
 const arr=i.experiments||[];
 return `<div class="grid cards">${metric("Experiments",arr.length)}${metric("Planned",arr.filter(x=>x.status==="Planned").length)}${metric("Running",arr.filter(x=>x.status==="Running").length)}${metric("Complete",arr.filter(x=>x.status==="Complete").length)}</div><div class="card" style="margin-top:18px"><div class="section-head" style="margin:0 0 12px"><div><h3>Experiment Library</h3><p class="status">Preserve hypothesis, method, result, unexpected outcomes, and lessons as one reasoning record.</p></div><button class="btn primary" onclick="openRecordDialog('experiment')">Add Experiment</button></div>${renderRecords("experiment",arr)}</div>`;
}

function renderCompare(i){
 const obs=i.observations||[];
 if(obs.length<2)return `<div class="empty">At least two observations are needed for comparison.</div>`;
 const selected=compareSelection.length===2?compareSelection:[obs[0].id,obs[1].id];
 compareSelection=selected;
 const a=obs.find(x=>x.id===selected[0]),b=obs.find(x=>x.id===selected[1]);
 return `<div class="card"><div class="section-head" style="margin:0 0 12px"><div><h3>Comparison Bench</h3><p class="status">Compare any two observations and record the differences.</p></div><button class="btn primary" onclick="openRecordDialog('change')">Record Change</button></div><div class="form-grid"><label>Observation A<select onchange="setCompare(0,this.value)">${obs.map(o=>`<option value="${o.id}" ${o.id===a.id?"selected":""}>${esc(o.title)}</option>`).join("")}</select></label><label>Observation B<select onchange="setCompare(1,this.value)">${obs.map(o=>`<option value="${o.id}" ${o.id===b.id?"selected":""}>${esc(o.title)}</option>`).join("")}</select></label></div><div class="compare-grid" style="margin-top:16px"><div class="compare-card"><div class="eyebrow">A</div><h3>${esc(a.title)}</h3><p>${esc(a.notes||"")}</p><div class="badges"><span class="badge">${esc(a.observedAt||"")}</span><span class="badge">${esc(a.location||"")}</span></div></div><div class="compare-card"><div class="eyebrow">B</div><h3>${esc(b.title)}</h3><p>${esc(b.notes||"")}</p><div class="badges"><span class="badge">${esc(b.observedAt||"")}</span><span class="badge">${esc(b.location||"")}</span></div></div></div></div>`;
}
function setCompare(idx,val){compareSelection[idx]=val;renderInquiry()}
function renderFriction(i){
 const arr=i.frictions||[];
 return `<div class="grid cards">${metric("Open",arr.filter(x=>x.status!=="Resolved").length)}${metric("High priority",arr.filter(x=>Number(x.priority)>=50).length)}${metric("With evidence",arr.filter(x=>x.evidenceId).length)}${metric("Resolved",arr.filter(x=>x.status==="Resolved").length)}</div><div class="card" style="margin-top:18px"><div class="section-head" style="margin:0 0 12px"><div><h3>Advanced Friction Analysis</h3><p class="status">Priority = frequency × severity × reach × confidence ÷ effort.</p></div><button class="btn primary" onclick="openRecordDialog('friction')">Add Friction</button></div>${renderRecords("friction",arr)}</div>`;
}
function renderCauses(i){
 const arr=i.rootCauses||[];
 return `<div class="card"><div class="section-head" style="margin:0 0 12px"><div><h3>Root Cause Explorer</h3><p class="status">Use 5 Whys, cause categories, contributing factors, and evidence confidence.</p></div><button class="btn primary" onclick="openRecordDialog('cause')">Add Analysis</button></div>${arr.length?arr.map(r=>`<div class="item"><div class="item-top"><div><h5>${esc(r.problem)}</h5><p>${esc(r.conclusion||"")}</p></div><button class="btn small danger" onclick="deleteRecord('cause','${r.id}')">Delete</button></div><div class="why-chain" style="margin-top:12px">${[r.why1,r.why2,r.why3,r.why4,r.why5].filter(Boolean).map((w,n)=>`<div class="why-node"><strong>Why ${n+1}</strong><br>${esc(w)}</div>`).join("")}</div><div class="fishbone" style="margin-top:14px">${["People","Process","Equipment","Environment","Materials","Unknown"].map(k=>`<div class="bone"><strong>${k}</strong><br><span class="status">${esc(r[k.toLowerCase()]||"No factor recorded")}</span></div>`).join("")}</div><div class="item-meta" style="margin-top:12px"><span class="badge">Confidence: ${esc(r.confidence||"Unknown")}</span><span class="badge">Evidence: ${esc(r.evidenceId||"None")}</span></div></div>`).join(""):`<div class="empty">No root cause analyses yet.</div>`}</div>`;
}


function renderInterventions(i){
 const arr=i.interventions||[],hist=i.interventionEvents||[];const actual=hist.map(x=>Number(String(x.actualCost||'').replace(/[^0-9.]/g,''))||0).reduce((a,b)=>a+b,0);
 return `<div class="grid cards">${metric("Proposed",arr.filter(x=>x.status==="Proposed").length)}${metric("In progress",arr.filter(x=>x.status==="In Progress").length)}${metric("Verified",hist.filter(x=>x.eventType==="Verification"||x.status==="Verified").length)}${metric("Actual cost",actual.toLocaleString())}</div><div class="split" style="margin-top:18px"><div class="card"><div class="section-head" style="margin:0 0 12px"><div><h3>Interventions</h3><p class="status">Plan deliberate changes with ownership, risk, expected cost, and success intent.</p></div><button class="btn primary" onclick="openRecordDialog('intervention')">Add Intervention</button></div>${renderRecords("intervention",arr)}</div><div class="card"><div class="section-head" style="margin:0 0 12px"><div><h3>Implementation history</h3><p class="status">Decisions, field changes, costs, checks, rollbacks, and verification.</p></div><button class="btn primary" onclick="openRecordDialog('interventionEvent')">Add History Entry</button></div>${hist.length?hist.slice().sort((a,b)=>String(b.eventDate||b.createdAt).localeCompare(String(a.eventDate||a.createdAt))).map(x=>`<div class="history-line ${x.eventType==='Verification'?'verification':''}"><strong>${esc(x.title||x.eventType)}</strong><p>${esc(x.notes||x.metric||'')}</p><div class="item-meta"><span class="badge">${esc(x.eventDate||'')}</span><span class="badge">${esc(x.eventType||'Update')}</span>${x.status?`<span class="badge">${esc(x.status)}</span>`:''}${x.actualCost?`<span class="badge">Cost ${esc(x.actualCost)}</span>`:''}${x.evidenceId?`<span class="badge">Evidence ${esc(x.evidenceId)}</span>`:''}</div><button class="btn small danger" onclick="deleteRecord('interventionEvent','${x.id}')">Delete</button></div>`).join(''):'<div class="empty">No implementation history yet.</div>'}</div></div>`;
}

function renderActions(i){
 const arr=i.actions||[];
 return `<div class="grid cards">${metric("Open",arr.filter(x=>x.status!=="Done").length)}${metric("Doing",arr.filter(x=>x.status==="Doing").length)}${metric("Blocked",arr.filter(x=>x.status==="Blocked").length)}${metric("Done",arr.filter(x=>x.status==="Done").length)}</div><div class="card" style="margin-top:18px"><div class="section-head" style="margin:0 0 12px"><div><h3>Action Tracker</h3><p class="status">Convert recommendations and interventions into owned work.</p></div><button class="btn primary" onclick="openRecordDialog('action')">Add Action</button></div>${renderRecords("action",arr)}</div>`;
}
function renderBacklog(i){
 const fr=(i.frictions||[]).map(x=>({...x,itemType:"Friction",score:Number(x.priority)||0}));
 const ints=(i.interventions||[]).map(x=>({...x,itemType:"Intervention",score:Math.round(((6-(Number(x.effort)||3))*(6-(Number(x.risk)||3))*10))}));
 const items=[...fr,...ints].sort((a,b)=>b.score-a.score);
 return `<div class="card"><div class="section-head" style="margin:0 0 12px"><div><h3>Improvement Backlog</h3><p class="status">A ranked view of problems and proposed changes. Friction uses priority score; interventions use low-effort, low-risk opportunity score.</p></div></div>${items.length?`<div class="item-list">${items.map((x,n)=>`<div class="item"><div class="item-top"><div><div class="eyebrow">#${n+1} ${esc(x.itemType)}</div><h5>${esc(x.title||"Untitled")}</h5><p>${esc(x.description||x.rationale||"")}</p></div><span class="badge">Score ${x.score}</span></div><div class="item-meta"><span class="badge">${esc(x.status||"Open")}</span>${x.owner?`<span class="badge">Owner: ${esc(x.owner)}</span>`:""}${x.cost?`<span class="badge">Cost: ${esc(x.cost)}</span>`:""}</div></div>`).join("")}</div>`:`<div class="empty">No backlog items yet.</div>`}</div>`;
}

function renderStakeholders(i){
 const arr=i.stakeholders||[],missing=arr.filter(x=>x.status!=="Engaged").length,q=(inf,impact)=>arr.filter(x=>x.influence===inf&&x.impact===impact);
 const chips=a=>a.map(x=>`<span class="quad-chip" title="${esc(x.role||"")}">${esc(x.name)}</span>`).join("")||'<span class="status">None</span>';
 return `<div class="grid cards">${metric("Stakeholders",arr.length)}${metric("Engaged",arr.filter(x=>x.status==="Engaged").length)}${metric("Missing input",missing)}${metric("High influence",arr.filter(x=>x.influence==="High").length)}</div><div class="split" style="margin-top:18px"><div class="card"><h3>Power–interest matrix</h3><div class="quadrant"><div class="quad"><h4>Manage closely</h4>${chips(q("High","High"))}</div><div class="quad"><h4>Keep satisfied</h4>${chips(q("High","Low"))}</div><div class="quad"><h4>Keep informed</h4>${chips(q("Low","High"))}</div><div class="quad"><h4>Monitor</h4>${chips(q("Low","Low"))}</div></div></div><div class="card"><div class="section-head" style="margin:0 0 12px"><div><h3>Stakeholder Register</h3><p class="status">Unknown and medium values remain in the register until classified.</p></div><button class="btn primary" onclick="openRecordDialog('stakeholder')">Add Stakeholder</button></div>${arr.length?arr.map(x=>`<div class="item"><div class="item-top"><div><strong>${esc(x.name)}</strong><p>${esc(x.role||"")}</p></div><button class="btn small danger" onclick="deleteRecord('stakeholder','${x.id}')">Delete</button></div><div class="item-meta"><span class="badge">${esc(x.group||"General")}</span><span class="badge">Influence ${esc(x.influence||"Unknown")}</span><span class="badge">Impact ${esc(x.impact||"Unknown")}</span><span class="badge">${esc(x.status||"Not contacted")}</span></div></div>`).join(""):'<div class="empty">No stakeholders.</div>'}</div></div>`
}
function renderGuides(i){
 const arr=i.interviewGuides||[];
 return `<div class="card"><div class="section-head" style="margin:0 0 12px"><div><h3>Interview Guides</h3><p class="status">Reusable question sets for consistent listening sessions.</p></div><button class="btn primary" onclick="openRecordDialog('guide')">Add Guide</button></div>${arr.length?arr.map(x=>`<div class="item"><div class="item-top"><div><div class="eyebrow">${esc(x.audience||"General")}</div><h5>${esc(x.title)}</h5><p>${esc(x.purpose||"")}</p></div><button class="btn small danger" onclick="deleteRecord('guide','${x.id}')">Delete</button></div><ol>${String(x.questions||"").split(/\n+/).filter(Boolean).map(q=>`<li>${esc(q.replace(/^[-•\d.\s]+/,""))}</li>`).join("")}</ol><div class="item-meta"><span class="badge">Method: ${esc(x.method||"Interview")}</span><span class="badge">Duration: ${esc(x.duration||"Not set")}</span></div></div>`).join(""):`<div class="empty">No interview guides yet.</div>`}</div>`;
}
function renderPerspectives(i){
 const arr=i.perspectives||[], stakeholders=i.stakeholders||[];
 return `<div class="grid cards">${metric("Perspectives",arr.length)}${metric("Stakeholder groups",new Set(arr.map(x=>x.group||x.participant)).size)}${metric("Minority views",arr.filter(x=>x.type==="Minority view").length)}${metric("Open questions",arr.filter(x=>x.type==="Question").length)}</div><div class="card" style="margin-top:18px"><div class="section-head" style="margin:0 0 12px"><div><h3>Perspective Map</h3><p class="status">Preserve observation, interpretation, concern, need, preference, dissent, and uncertainty without forcing consensus.</p></div><button class="btn primary" onclick="openRecordDialog('listen')">Add Perspective</button></div>${arr.length?`<div class="perspective-map"><table class="perspective-table"><thead><tr><th>Participant</th><th>Theme</th><th>Type</th><th>Position</th><th>Perspective</th><th>Confidence</th></tr></thead><tbody>${arr.map(x=>`<tr><td>${esc(x.participant)}</td><td>${esc(x.theme||"Uncoded")}</td><td>${esc(x.type||"")}</td><td><span class="signal ${x.position==="Agree"?"agree":x.position==="Disagree"?"disagree":"mixed"}">${esc(x.position||"Mixed")}</span></td><td>${esc(x.perspective||"")}</td><td>${esc(x.confidence||"")}%</td></tr>`).join("")}</tbody></table></div>${renderRecords("listen",arr)}`:`<div class="empty">No perspectives have been recorded.</div>`}</div>`;
}
function themeCounts(i){
 const manual=(i.themes||[]).map(t=>({name:t.name,count:Number(t.count)||0,definition:t.definition||"",status:t.status||"Active"}));
 const map={};(i.perspectives||[]).forEach(p=>String(p.theme||"").split(",").map(x=>x.trim()).filter(Boolean).forEach(t=>map[t]=(map[t]||0)+1));
 Object.entries(map).forEach(([name,count])=>{const found=manual.find(x=>x.name.toLowerCase()===name.toLowerCase());if(found)found.count=Math.max(found.count,count);else manual.push({name,count,definition:"Derived from coded perspectives",status:"Derived"})});
 return manual.sort((a,b)=>b.count-a.count);
}
function renderCoding(i){
 const themes=themeCounts(i),pers=i.perspectives||[],pairs={};pers.forEach(p=>{const ts=String(p.theme||"").split(",").map(x=>x.trim()).filter(Boolean);for(let a=0;a<ts.length;a++)for(let b=a+1;b<ts.length;b++){const k=[ts[a],ts[b]].sort().join(" ↔ ");pairs[k]=(pairs[k]||0)+1}});const pairList=Object.entries(pairs).sort((a,b)=>b[1]-a[1]);
 return `<div class="split"><div class="card"><div class="section-head" style="margin:0 0 12px"><div><h3>Thematic Coding Engine</h3><p class="status">Group recurring concerns, ideas, risks, successes, and questions.</p></div><button class="btn primary" onclick="openRecordDialog('theme')">Add Theme</button></div>${themes.length?`<div class="theme-cloud">${themes.map(t=>`<span class="theme-chip"><strong>${esc(t.name)}</strong> · ${t.count}</span>`).join("")}</div>`:'<div class="empty">Add themes or code perspectives.</div>'}<h3 style="margin-top:22px">Theme co-occurrence</h3>${pairList.length?pairList.slice(0,12).map(([k,v])=>`<div class="item"><strong>${esc(k)}</strong><span style="float:right">${v}</span></div>`).join(""):'<div class="empty">Assign multiple comma-separated themes to reveal relationships.</div>'}</div><div class="card"><h3>Codebook</h3>${(i.themes||[]).length?(i.themes||[]).map(t=>`<div class="item"><div class="item-top"><div><h5>${esc(t.name)}</h5><p>${esc(t.definition||"")}</p></div><button class="btn small danger" onclick="deleteRecord('theme','${t.id}')">Delete</button></div><div class="item-meta"><span class="badge">${esc(t.category||"General")}</span><span class="badge">${esc(t.status||"Active")}</span></div></div>`).join(""):'<div class="empty">No formal codebook entries.</div>'}</div></div>`
}
function renderConsensus(i){
 const arr=i.perspectives||[], themes=[...new Set(arr.flatMap(x=>String(x.theme||"Uncoded").split(",").map(y=>y.trim()).filter(Boolean)))];
 const rows=themes.map(theme=>{const ps=arr.filter(x=>String(x.theme||"Uncoded").split(",").map(y=>y.trim()).includes(theme));const agree=ps.filter(x=>x.position==="Agree").length,disagree=ps.filter(x=>x.position==="Disagree").length,mixed=ps.length-agree-disagree;let label="Insufficient input",score=0;if(ps.length){score=Math.round(Math.max(agree,disagree,mixed)/ps.length*100);label=agree>disagree&&agree>=mixed?"Agreement":disagree>agree&&disagree>=mixed?"Disagreement":"Mixed"}return {theme,ps,agree,disagree,mixed,label,score}});
 return `<div class="card"><div class="section-head" style="margin:0 0 12px"><div><h3>Consensus Explorer</h3><p class="status">Shows convergence, disagreement, minority views, and uncertainty. Majority opinion is not treated as proof.</p></div></div>${rows.length?rows.map(r=>`<div class="consensus-row"><strong>${esc(r.theme)}</strong><div><div class="bar"><span style="width:${r.score}%"></span></div><div class="status">Agree ${r.agree} · Disagree ${r.disagree} · Mixed ${r.mixed}</div></div><span class="signal ${r.label==="Agreement"?"agree":r.label==="Disagreement"?"disagree":"mixed"}">${r.label}</span></div>`).join(""):`<div class="empty">Assign themes and positions to perspectives to reveal consensus patterns.</div>`}<div class="notice" style="margin-top:16px">Minority views retained: ${arr.filter(x=>x.type==="Minority view").length}. High-confidence contradictions: ${arr.filter(x=>x.type==="Contradiction"&&Number(x.confidence)>=70).length}.</div></div>`;
}

function openInquiryDialog(){inquiryDialogTitle.textContent="New Inquiry";inquiryForm.reset();inqId.value="";inquiryDialog.showModal()}
function editInquiry(id){const i=state.inquiries.find(x=>x.id===id);if(!i)return;inquiryDialogTitle.textContent="Edit Inquiry";["Id","Title","Subject","Question","Location","Owner","Outcome","Baseline"].forEach(k=>document.getElementById("inq"+k).value=i[k.toLowerCase()]||"");inquiryDialog.showModal()}
inquiryForm.addEventListener("submit",e=>{e.preventDefault();const id=inqId.value,data={id:id||uid(),title:inqTitle.value.trim(),subject:inqSubject.value.trim(),question:inqQuestion.value.trim(),location:inqLocation.value.trim(),owner:inqOwner.value.trim(),outcome:inqOutcome.value.trim(),baseline:inqBaseline.value.trim(),updatedAt:now()};if(id)Object.assign(state.inquiries.find(x=>x.id===id),data);else state.inquiries.push({...data,createdAt:now(),archived:false,observations:[],evidence:[],stations:[],changes:[],frictions:[],rootCauses:[],interventionEvents:[],interventions:[],actions:[],stakeholders:[],interviewGuides:[],perspectives:[],themes:[],forecasts:[],assumptions:[],experiments:[],inferences:[],hypotheses:[],relationships:[],lessons:[],reviews:[]});saveState();inquiryDialog.close();render()});

const schemas={
 observe:[["title","Observation title","text"],["notes","What did you observe?","textarea"],["location","Location","text"],["stationId","Station ID","text"],["observedAt","Observed date","date"],["weather","Conditions","text"],["measurement","Measurement or reading","text"]],
 evidence:[["title","Evidence title","text"],["type","Type","select","Note|Photo|Drawing|Document|URL|Measurement|Audio reference"],["notes","Description","textarea"],["url","URL or reference","text"],["tags","Tags","text"],["file","Optional image file","file"]],
 station:[["name","Station name","text"],["location","Location","text"],["prompts","Standard prompts","textarea"],["measurements","Required measurements","textarea"],["interval","Revisit interval","text"],["nextVisit","Next visit","date"],["status","Status","select","Active|Paused|Retired"]],
 change:[["title","Change title","text"],["description","Before and after summary","textarea"],["category","Category","select","Growth|Wear|Damage|Repair|Replacement|Seasonal|Unexpected|Unknown"],["severity","Severity 1–5","number"],["confidence","Confidence %","number"],["impact","Impact","select","Beneficial|Harmful|Neutral|Uncertain"],["observationA","Observation A ID","text"],["observationB","Observation B ID","text"]],
 friction:[["title","Friction title","text"],["description","What happened?","textarea"],["category","Category","text"],["discovered","Discovery date","date"],["frequency","Frequency 1–5","number"],["severity","Severity 1–5","number"],["reach","Reach 1–5","number"],["confidence","Confidence %","number"],["effort","Resolution effort 1–5","number"],["cost","Estimated cost","text"],["owner","Owner","text"],["status","Status","select","Open|Investigating|Planned|Resolved|Deferred"],["workaround","Current workaround","textarea"],["evidenceId","Supporting evidence ID","text"]],
 cause:[["problem","Problem statement","textarea"],["why1","Why 1","textarea"],["why2","Why 2","textarea"],["why3","Why 3","textarea"],["why4","Why 4","textarea"],["why5","Why 5","textarea"],["people","People factors","textarea"],["process","Process factors","textarea"],["equipment","Equipment factors","textarea"],["environment","Environment factors","textarea"],["materials","Material factors","textarea"],["unknown","Unknown factors","textarea"],["confidence","Evidence confidence","select","High|Medium|Low|Unknown"],["evidenceId","Evidence ID","text"],["conclusion","Most likely root cause","textarea"]],
 intervention:[["title","Intervention title","text"],["description","What will change?","textarea"],["rationale","Why this intervention?","textarea"],["owner","Owner","text"],["startDate","Start date","date"],["endDate","End date","date"],["cost","Estimated cost","text"],["effort","Effort 1–5","number"],["risk","Risk 1–5","number"],["status","Status","select","Proposed|Approved|In Progress|Completed|Cancelled"],["frictionId","Related friction ID","text"],["forecastId","Related forecast ID","text"],["notes","Implementation notes","textarea"]],
 interventionEvent:[["title","History entry title","text"],["interventionId","Related intervention ID","text"],["eventDate","Event date","date"],["eventType","Event type","select","Decision|Implementation|Check|Change|Rollback|Verification|Cost update"],["status","Resulting status","select","Proposed|Approved|In Progress|Completed|Rolled Back|Verified|Failed"],["actualCost","Actual cost or cost update","text"],["metric","Measured result","text"],["notes","What happened?","textarea"],["evidenceId","Verification evidence ID","text"]],
 action:[["title","Action title","text"],["description","Action description","textarea"],["owner","Owner","text"],["dueDate","Due date","date"],["priority","Priority","select","Low|Medium|High|Critical"],["status","Status","select","Open|Doing|Waiting|Blocked|Done"],["interventionId","Related intervention ID","text"],["frictionId","Related friction ID","text"]],
 stakeholder:[["name","Stakeholder name","text"],["group","Stakeholder group","text"],["role","Role or relationship","text"],["influence","Influence","select","High|Medium|Low|Unknown"],["impact","Level affected","select","High|Medium|Low|Unknown"],["status","Engagement status","select","Not contacted|Invited|Engaged|Declined|Missing"],["contactDate","Last contact date","date"],["notes","Notes and access considerations","textarea"]],
 guide:[["title","Guide title","text"],["audience","Target audience","text"],["purpose","Purpose","textarea"],["method","Method","select","Interview|Walkthrough|Focus group|Critique|Public meeting|Observation debrief"],["duration","Expected duration","text"],["questions","Questions, one per line","textarea"]],
 theme:[["name","Theme name","text"],["definition","Definition and inclusion criteria","textarea"],["category","Category","select","Concern|Idea|Risk|Success|Question|Need|Other"],["status","Status","select","Active|Provisional|Merged|Retired"],["count","Starting count","number"]],
 listen:[["participant","Participant or group","text"],["group","Stakeholder group","text"],["perspective","Perspective","textarea"],["theme","Theme or themes, comma separated","text"],["type","Type","select","Observation|Interpretation|Concern|Need|Preference|Question|Recommendation|Contradiction|Minority view"],["position","Position","select","Agree|Disagree|Mixed|Uncertain"],["confidence","Confidence %","number"],["evidenceId","Related evidence ID","text"]],
 predict:[["prediction","Prediction","textarea"],["forecastType","Forecast type","select","Binary|Numeric|Range|Schedule|Comparative|Directional"],["targetDate","Target date","date"],["confidence","Confidence %","number"],["assumptions","Assumptions","textarea"],["indicators","Indicators","textarea"],["status","Status","select","Open|Watching|Resolved|Cancelled"]],
 assumption:[["title","Assumption","textarea"],["domain","Domain","text"],["forecastId","Related forecast ID","text"],["evidenceId","Evidence ID","text"],["status","Current finding","select","Unknown|True|False|Mixed"],["confidence","Confidence %","number"],["notes","Validation notes","textarea"]],
 experiment:[["title","Experiment title","text"],["hypothesis","Hypothesis","textarea"],["method","Method","textarea"],["measure","Success measure","textarea"],["startDate","Start date","date"],["endDate","End date","date"],["status","Status","select","Planned|Running|Complete|Cancelled"],["result","Result","textarea"],["unexpected","Unexpected outcomes","textarea"],["lessons","Lessons","textarea"]],
 inference:[["title","Inference title","text"],["inference","What do the observations suggest?","textarea"],["evidenceIds","Supporting evidence IDs, comma separated","textarea"],["confidence","Confidence %","number"],["alternatives","Alternative interpretations","textarea"]],
 hypothesis:[["title","Hypothesis title","text"],["hypothesis","Proposed explanation","textarea"],["basis","Reasoning and supporting evidence","textarea"],["test","What would test or falsify it?","textarea"],["confidence","Confidence %","number"],["status","Status","select","Proposed|Testing|Supported|Weakened|Rejected"]],
 relationship:[["fromId","From record ID","text"],["relation","Relationship","select","supports|contradicts|explains|causes|tests|responds to|results in|learned from"],["toId","To record ID","text"],["notes","Relationship notes","textarea"]],
 lesson:[["title","Lesson title","text"],["lesson","What should be carried forward?","textarea"],["scope","Applies to","select","This inquiry|Similar inquiries|Organization-wide"],["confidence","Confidence %","number"],["evidenceIds","Supporting record IDs","textarea"]],
 review:[["title","Review title","text"],["outcome","Actual outcome","textarea"],["comparison","Expected versus actual","textarea"],["lessons","Lessons learned","textarea"],["nextAction","Recommended action","textarea"]]
};
function openRecordDialog(type){
 recordType.value=type;recordDialogTitle.textContent="Add "+type[0].toUpperCase()+type.slice(1)+" Record";
 recordFields.innerHTML=`<div class="form-grid">${schemas[type].map(([n,l,t,o])=>{if(t==="textarea")return `<label style="grid-column:1/-1">${l}<textarea name="${n}"></textarea></label>`;if(t==="select")return `<label>${l}<select name="${n}">${o.split("|").map(x=>`<option>${x}</option>`).join("")}</select></label>`;return `<label>${l}<input name="${n}" type="${t}" ${t==="number"?'min="0" max="100"':''}></label>`}).join("")}</div>`;
 recordDialog.showModal();
 setTimeout(()=>{applyCapturedLocation();if(state.fieldVoiceNote){const ta=recordFields.querySelector("textarea");if(ta&&!ta.value)ta.value=state.fieldVoiceNote;state.fieldVoiceNote="";}},0);
}
recordForm.addEventListener("submit",async e=>{
 e.preventDefault();const i=getInquiry();if(!i)return;const type=recordType.value,fd=new FormData(e.target),r={id:uid(),createdAt:now()};
 for(const [k,v] of fd.entries()){if(k==="file"&&v instanceof File&&v.size){r.dataUrl=await fileToDataUrl(v)}else if(k!=="file")r[k]=v}
 if(type==="friction"){const base=(Number(r.frequency)||0)*(Number(r.severity)||0)*(Number(r.reach)||0)*(Number(r.confidence)||0)/100;r.priority=Math.round(base/Math.max(1,Number(r.effort)||1))}
 if(type==="change"&&compareSelection.length===2){r.observationA=compareSelection[0];r.observationB=compareSelection[1]}
 const key={observe:"observations",evidence:"evidence",station:"stations",change:"changes",friction:"frictions",cause:"rootCauses",intervention:"interventions",interventionEvent:"interventionEvents",action:"actions",stakeholder:"stakeholders",guide:"interviewGuides",theme:"themes",listen:"perspectives",predict:"forecasts",assumption:"assumptions",experiment:"experiments",inference:"inferences",hypothesis:"hypotheses",relationship:"relationships",lesson:"lessons",review:"reviews"}[type];
 i[key].push(r);i.updatedAt=now();saveState();recordDialog.close();e.target.reset();renderInquiry();
});
function fileToDataUrl(file){return new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(reader.result);reader.onerror=reject;reader.readAsDataURL(file)})}
function deleteRecord(type,id){const i=getInquiry(),key={observe:"observations",evidence:"evidence",station:"stations",change:"changes",friction:"frictions",cause:"rootCauses",intervention:"interventions",interventionEvent:"interventionEvents",action:"actions",stakeholder:"stakeholders",guide:"interviewGuides",theme:"themes",listen:"perspectives",predict:"forecasts",assumption:"assumptions",experiment:"experiments",inference:"inferences",hypothesis:"hypotheses",relationship:"relationships",lesson:"lessons",review:"reviews"}[type];i[key]=i[key].filter(x=>x.id!==id);saveState();renderInquiry()}
function toggleArchive(id){const i=state.inquiries.find(x=>x.id===id);i.archived=!i.archived;saveState();currentView=i.archived?"archive":"inquiries";render()}
function fieldCapture(){const id=fieldInquiry.value;if(!id)return;currentInquiryId=id;currentView="inquiry";currentTab="observe";render();openRecordDialog("observe")}
function fieldEvidence(){const id=fieldInquiry.value;if(!id)return;currentInquiryId=id;currentView="inquiry";currentTab="evidence";render();openRecordDialog("evidence")}
function visitStation(iid,sid){currentInquiryId=iid;currentView="inquiry";currentTab="observe";render();openRecordDialog("observe");setTimeout(()=>{const x=recordFields.querySelector('[name="stationId"]');if(x)x.value=sid},0)}
function fieldQuick(type){const id=fieldInquiry.value;if(!id)return;currentInquiryId=id;currentView="inquiry";currentTab=type==='listen'?'listen':type==='friction'?'diagnose':type==='action'?'actions':type==='change'?'changes':'observe';render();openRecordDialog(type);setTimeout(applyCapturedLocation,0)}
function captureLocation(){if(!navigator.geolocation)return alert('Geolocation is not available in this browser.');fieldLocation.textContent='Capturing location…';navigator.geolocation.getCurrentPosition(p=>{state.fieldLocation={latitude:p.coords.latitude.toFixed(6),longitude:p.coords.longitude.toFixed(6),accuracy:Math.round(p.coords.accuracy),capturedAt:now()};saveState();fieldLocation.textContent=`${state.fieldLocation.latitude}, ${state.fieldLocation.longitude} · accuracy ±${state.fieldLocation.accuracy} m`;},e=>fieldLocation.textContent='Location unavailable: '+e.message,{enableHighAccuracy:true,timeout:10000})}
function applyCapturedLocation(){const loc=state.fieldLocation;if(!loc||!window.recordFields)return;const location=recordFields.querySelector('[name="location"]');if(location&&!location.value)location.value=`${loc.latitude}, ${loc.longitude}`;const lat=recordFields.querySelector('[name="latitude"]'),lon=recordFields.querySelector('[name="longitude"]');if(lat)lat.value=loc.latitude;if(lon)lon.value=loc.longitude}
function startVoiceNote(){const SR=window.SpeechRecognition||window.webkitSpeechRecognition;if(!SR)return alert('Voice transcription is not supported by this browser.');const r=new SR();r.lang='en-US';r.interimResults=false;r.onresult=e=>{state.fieldVoiceNote=e.results[0][0].transcript;alert('Voice note captured. It will be inserted into the next open record form.');};r.onerror=e=>alert('Voice capture failed: '+e.error);r.start()}
function openMap(lat,lon){window.open(`https://www.openstreetmap.org/?mlat=${encodeURIComponent(lat)}&mlon=${encodeURIComponent(lon)}#map=18/${encodeURIComponent(lat)}/${encodeURIComponent(lon)}`,'_blank')}
function printStationCard(iid,sid){const i=state.inquiries.find(x=>x.id===iid),s=i&&(i.stations||[]).find(x=>x.id===sid);if(!s)return;const w=window.open('','_blank');w.document.write(`<title>${esc(s.name)} Station Card</title><style>body{font-family:system-ui;padding:32px;max-width:700px;margin:auto}h1{font-size:28px}.code{font-family:monospace;border:2px solid;padding:14px;font-size:18px}.box{border:1px solid #bbb;padding:14px;margin:12px 0}</style><h1>${esc(s.name)}</h1><p>${esc(i.title)}</p><div class="code">DRIFT-STATION:${esc(s.id)}</div><div class="box"><strong>Location</strong><p>${esc(s.location||'')}</p><strong>Photo angle</strong><p>${esc(s.photoAngle||'')}</p></div><div class="box"><strong>Prompts</strong><p>${esc(s.prompts||'')}</p><strong>Required measurements</strong><p>${esc(s.measurements||'')}</p><strong>Checklist</strong><p>${esc(s.checklist||'')}</p></div>`);w.document.close();w.print()}
function clearAllData(){if(confirm("Delete all Drift data stored in this browser?")){state=blankState();saveState();render()}}

function loadDemo(){
 const id=uid(),ev1=uid(),st1=uid(),o1=uid(),o2=uid(),f1=uid();
 state.inquiries.push({id,title:"Workshop Entrance Wayfinding",subject:"Usability Friction Study",question:"Why do first-time visitors struggle to find the workshop entrance?",location:"Mountain Maryland Makers workshop",owner:"Field Team",outcome:"Reduce wayfinding failures below 15%.",baseline:"Approximately one in three first-time visitors asks for directions.",createdAt:now(),updatedAt:now(),archived:false,
 observations:[{id:o1,title:"Afternoon arrival study",notes:"Four of twelve visitors walked past the side entrance before turning around.",location:"South approach",stationId:st1,observedAt:"2026-07-08",measurement:"4 of 12 missed entrance",createdAt:now()},{id:o2,title:"Evening visibility check",notes:"The existing door sign is difficult to read after sunset.",location:"Workshop entrance",stationId:st1,observedAt:"2026-07-09",measurement:"Sign readable at 18 ft",createdAt:now()}],
 evidence:[{id:ev1,title:"Visitor arrival tally",type:"Measurement",notes:"Twelve first-time arrivals observed; four missed the entrance.",tags:"wayfinding, baseline",createdAt:now()}],
 stations:[{id:st1,name:"South Approach Station",location:"Sidewalk south of workshop",prompts:"Can the entrance be identified without stopping? Is the sign visible?",measurements:"Missed entrance count; sign readability distance",interval:"Weekly",nextVisit:"2026-07-15",status:"Active",createdAt:now()}],
 changes:[{id:uid(),title:"Evening visibility loss",description:"The entrance is recognizable in daylight but becomes ambiguous after sunset.",category:"Cyclical",severity:"3",confidence:"90",impact:"Harmful",observationA:o1,observationB:o2,createdAt:now()}],
 frictions:[{id:f1,title:"Entrance sign missed",description:"Visitors do not recognize the side door as the public entrance.",category:"Wayfinding",discovered:"2026-07-08",frequency:"4",severity:"3",reach:"4",confidence:"85",effort:"2",cost:"$250–$500",owner:"Facilities",status:"Investigating",workaround:"Call the host or ask a nearby tenant.",evidenceId:ev1,priority:20,createdAt:now()}],
 rootCauses:[{id:uid(),problem:"Visitors miss the public entrance.",why1:"The entrance does not visually read as public.",why2:"The sign is mounted flat to the wall.",why3:"It cannot be seen from the primary walking direction.",why4:"The original sign plan assumed visitors would approach head-on.",why5:"Arrival paths were not observed before installation.",people:"Visitors are unfamiliar with the building.",process:"No field validation of arrival routes.",equipment:"Flat wall sign.",environment:"Low evening contrast.",materials:"Reflectivity is limited.",unknown:"Effect of parked vehicles.",confidence:"High",evidenceId:ev1,conclusion:"The sign orientation does not match actual arrival paths.",createdAt:now()}],
 interventions:[{id:uid(),title:"Projecting entrance sign",description:"Install a double-sided projecting sign and paint a contrasting threshold.",rationale:"Address the confirmed sign-orientation root cause.",owner:"Facilities",startDate:"2026-07-20",endDate:"2026-07-30",cost:"$425",effort:"2",risk:"1",status:"Approved",frictionId:f1,forecastId:"",notes:"Verify visibility from both sidewalk approaches.",createdAt:now()}],
 stakeholders:[{id:uid(),name:"First-time visitors",group:"Visitors",role:"Primary affected users",influence:"Medium",impact:"High",status:"Engaged",contactDate:"2026-07-09",notes:"Recruit a mix of daytime and evening arrivals.",createdAt:now()},{id:uid(),name:"Workshop volunteers",group:"Operations",role:"Hosts and greeters",influence:"High",impact:"Medium",status:"Engaged",contactDate:"2026-07-09",notes:"Observe recurring arrival questions.",createdAt:now()},{id:uid(),name:"Adjacent tenants",group:"Neighbors",role:"Informal wayfinding support",influence:"Low",impact:"Medium",status:"Invited",contactDate:"2026-07-10",notes:"Often redirect lost visitors.",createdAt:now()}],
 interviewGuides:[{id:uid(),title:"First Arrival Walkthrough",audience:"First-time visitors",purpose:"Understand what cues visitors notice while approaching the building.",method:"Walkthrough",duration:"15 minutes",questions:"Show me where you think the public entrance is.\nWhat visual cue influenced that choice?\nWhen did you first feel uncertain?\nWhat would have made the route obvious?",createdAt:now()}],
 themes:[{id:uid(),name:"Entrance appears private",definition:"Comments indicating the doorway lacks public or welcoming cues.",category:"Concern",status:"Active",count:"2",createdAt:now()},{id:uid(),name:"Sign orientation",definition:"Comments about sign visibility from actual arrival paths.",category:"Risk",status:"Active",count:"2",createdAt:now()}],
 actions:[{id:uid(),title:"Obtain sign fabrication quote",description:"Request two quotes for a weather-resistant projecting sign.",owner:"Facilities",dueDate:"2026-07-18",priority:"High",status:"Doing",interventionId:"",frictionId:f1,createdAt:now()}],
 perspectives:[{id:uid(),participant:"First-time visitors",group:"Visitors",perspective:"The building number is visible, but the entrance looks private.",theme:"Entrance appears private",type:"Concern",position:"Agree",confidence:"85",evidenceId:ev1,createdAt:now()},{id:uid(),participant:"Workshop volunteers",group:"Operations",perspective:"A projecting sign would be easier to see from the sidewalk.",theme:"Sign orientation",type:"Recommendation",position:"Agree",confidence:"80",evidenceId:ev1,createdAt:now()},{id:uid(),participant:"Adjacent tenant",group:"Neighbors",perspective:"The current entrance is clear once the exterior lights turn on.",theme:"Entrance appears private",type:"Minority view",position:"Disagree",confidence:"65",evidenceId:"",createdAt:now()}],
 assumptions:[{id:uid(),title:"The projecting sign is visible from both sidewalk approaches.",domain:"Wayfinding",forecastId:"",evidenceId:ev1,status:"Unknown",confidence:"70",notes:"Validate after installation using the two observation paths.",createdAt:now()},{id:uid(),title:"Visitor volume remains representative during the measurement period.",domain:"Measurement",forecastId:"",evidenceId:ev1,status:"Mixed",confidence:"60",notes:"Weekend events may create a different arrival pattern.",createdAt:now()}],
 experiments:[{id:uid(),title:"Temporary projecting sign trial",hypothesis:"A projecting cue will reduce missed entrances during first arrival.",method:"Install a temporary double-sided sign for one week and observe 20 first-time arrivals.",measure:"Fewer than 3 of 20 visitors miss the entrance.",startDate:"2026-07-20",endDate:"2026-07-27",status:"Planned",result:"",unexpected:"",lessons:"",createdAt:now()}],
 forecasts:[{id:uid(),prediction:"A projecting sign and painted threshold will reduce wayfinding failures below 15%.",forecastType:"Binary",targetDate:"2026-08-15",confidence:"70",assumptions:"Visible from both approaches; visitor volume remains typical",indicators:"Wrong-door attempts; direction requests",status:"Open",createdAt:now()},{id:uid(),prediction:"At least one temporary sign location will be visible from both approach paths.",forecastType:"Binary",targetDate:"2026-07-25",confidence:"80",assumptions:"No parked vehicle blocks the sightline",indicators:"Visibility check from marked approach points",status:"Resolved",outcomeBinary:"1",actualOutcome:"The projecting location remained visible from both marked approach points.",resolvedDate:"2026-07-25",createdAt:now()}],inferences:[{id:uid(),title:"Arrival-path inference",inference:"Visitors decide whether an entrance is public before reaching the doorway, using sign orientation and threshold cues.",evidenceIds:ev1,confidence:"85",alternatives:"Low lighting may independently explain some failures.",createdAt:now()}],hypotheses:[{id:uid(),title:"Orientation mismatch hypothesis",hypothesis:"The flat-mounted sign fails because it is not visible from the dominant approach path.",basis:"Observed missed entrances and stakeholder comments consistently reference visibility and a private appearance.",test:"Install a temporary projecting sign and measure missed entrances.",confidence:"80",status:"Testing",createdAt:now()}],relationships:[],lessons:[{id:uid(),title:"Validate from actual approach paths",lesson:"Wayfinding elements should be evaluated from observed arrival paths rather than from the installation point alone.",scope:"Similar inquiries",confidence:"90",evidenceIds:ev1,createdAt:now()}],reviews:[]});
 saveState();currentInquiryId=id;currentView="inquiry";currentTab="overview";render();
}

document.querySelectorAll(".nav button").forEach(b=>b.onclick=()=>{currentView=b.dataset.view;render()});
document.querySelectorAll("[data-close]").forEach(b=>b.onclick=()=>document.getElementById(b.dataset.close).close());
newInquiryBtn.onclick=openInquiryDialog;loadDemoBtn.onclick=loadDemo;
themeBtn.onclick=()=>{state.theme=state.theme==="dark"?"light":"dark";setTheme();saveState()};
quickCaptureBtn.onclick=()=>{const first=activeInquiries()[0];if(!first){openInquiryDialog();return}currentInquiryId=first.id;currentView="inquiry";currentTab="observe";render();openRecordDialog("observe")};
exportBtn.onclick=()=>{const blob=new Blob([JSON.stringify(state,null,2)],{type:"application/json"}),a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download=`drift-v5-foundation-backup-${new Date().toISOString().slice(0,10)}.json`;a.click();URL.revokeObjectURL(a.href)};
importBtn.onclick=()=>importFile.click();
importFile.onchange=async e=>{try{const data=JSON.parse(await e.target.files[0].text());state={...blankState(),...data};saveState();setTheme();render();alert("Import complete.")}catch(err){alert("Could not import this file: "+err.message)}finally{e.target.value=""}};
