// Drift v7.1.0 Guided Inquiry Copilot
(function(){
const COPILOT_STAGES=['Observe','Understand','Improve','Learn'];
const COPILOT_ARRAYS=['observations','evidence','changes','frictions','rootCauses','inferences','hypotheses','perspectives','stakeholders','forecasts','assumptions','experiments','interventions','interventionEvents','actions','reviews','lessons'];
function list(i,a){return i[a]||[]}
function label(r){return typeof recordLabel==='function'?recordLabel(r):(r.title||r.name||r.prediction||r.assumption||r.problem||r.participant||'Record')}
function recordById(i,id){if(!id)return null;for(const a of COPILOT_ARRAYS){const r=list(i,a).find(x=>x.id===id);if(r)return{array:a,record:r}}return null}
function hasEvidence(i,r){if(!r)return false;if(r.evidenceId||r.evidenceIds)return true;return list(i,'relationships').some(x=>(x.fromId===r.id||x.toId===r.id)&&[x.fromId,x.toId].some(id=>list(i,'evidence').some(e=>e.id===id)))}
function rec(kind,priority,title,why,confidence,benefit,action,triggerIds,stage){return{kind,priority,title,why,confidence,benefit,action,triggerIds:(triggerIds||[]).filter(Boolean),stage}}
function currentStage(i){
 if(!list(i,'observations').length||!list(i,'evidence').length)return'Observe';
 if(!list(i,'frictions').length||(!list(i,'inferences').length&&!list(i,'hypotheses').length))return'Understand';
 if(!list(i,'interventions').length&&!list(i,'experiments').length)return'Improve';
 return'Learn';
}
function buildRecommendations(i){
 const out=[], today=Date.now();
 const observations=list(i,'observations'), evidence=list(i,'evidence'), frictions=list(i,'frictions'), roots=list(i,'rootCauses'), inferences=list(i,'inferences'), hypotheses=list(i,'hypotheses'), stakeholders=list(i,'stakeholders'), perspectives=list(i,'perspectives'), forecasts=list(i,'forecasts'), assumptions=list(i,'assumptions'), interventions=list(i,'interventions'), events=list(i,'interventionEvents'), reviews=list(i,'reviews'), lessons=list(i,'lessons'), actions=list(i,'actions');
 if(!observations.length)out.push(rec('Next observation','high','Establish a direct field observation','The inquiry has no observation record, so later conclusions cannot be traced back to a documented condition.',96,'Creates the factual starting point for the inquiry.','observation',[], 'Observe'));
 else if(observations.length<2)out.push(rec('Next observation','medium','Repeat the observation under a different condition',`Only one observation exists: “${label(observations[0])}.” A second visit would help separate a persistent condition from a one-time event.`,86,'Improves comparison and change detection.','observation',[observations[0].id],'Observe'));
 const unsupported=[...frictions,...inferences,...hypotheses].filter(r=>!hasEvidence(i,r));
 if(!evidence.length)out.push(rec('Missing evidence','high','Capture evidence for the inquiry','No reusable evidence record exists. Important findings currently depend on narrative records alone.',97,'Improves auditability and report credibility.','evidence',[observations[0]?.id],'Observe'));
 else if(unsupported.length)out.push(rec('Missing evidence','high','Link evidence to an unsupported finding',`${unsupported.length} diagnostic or reasoning record${unsupported.length===1?' is':'s are'} not connected to evidence. The first is “${label(unsupported[0])}.”`,91,'Strengthens traceability and confidence calibration.','evidence',[unsupported[0].id],'Observe'));
 if(frictions.length&&!hypotheses.length){const f=[...frictions].sort((a,b)=>Number(b.priority||0)-Number(a.priority||0))[0];out.push(rec('Candidate hypothesis','high',`Explain why “${label(f)}” occurs`,`The inquiry has documented friction but no hypothesis that can be tested. The proposed hypothesis should explain the observed mechanism rather than merely restate the problem.`,88,'Creates a testable bridge from diagnosis to intervention.','hypothesis',[f.id,roots[0]?.id,inferences[0]?.id],'Understand'))}
 else if(inferences.length&&!hypotheses.length){out.push(rec('Candidate hypothesis','medium',`Convert “${label(inferences[0])}” into a testable explanation`,'An inference exists, but no hypothesis specifies what mechanism would account for it or what evidence would weaken it.',84,'Makes the reasoning chain falsifiable.','hypothesis',[inferences[0].id],'Understand'))}
 const represented=new Set(perspectives.map(p=>String(p.group||p.stakeholder||p.participant||'').toLowerCase()).filter(Boolean));
 const missingStake=stakeholders.find(s=>!represented.has(String(s.name||'').toLowerCase())&&!represented.has(String(s.group||'').toLowerCase()));
 if(!stakeholders.length)out.push(rec('Stakeholder gap','medium','Identify who is affected and who can influence the outcome','No stakeholder records exist, so perspective coverage and implementation ownership cannot be evaluated.',82,'Reduces blind spots and improves adoption.','stakeholder',[],'Understand'));
 else if(missingStake)out.push(rec('Stakeholder gap','medium',`Collect input from ${label(missingStake)}`,`This stakeholder is registered but has no matching perspective record. Their influence or impact may make the omission material.`,79,'Improves representation and contradiction discovery.','perspective',[missingStake.id],'Understand'));
 const forecastNoAssumption=forecasts.find(f=>!f.assumptions&&!assumptions.some(a=>a.forecastId===f.id));
 if(forecastNoAssumption)out.push(rec('Assumption test','high',`Document assumptions behind “${label(forecastNoAssumption)}”`,'A forecast without explicit assumptions is difficult to interpret when the outcome differs from expectations.',93,'Improves calibration and post-outcome learning.','assumption',[forecastNoAssumption.id],'Improve'));
 const vagueForecast=forecasts.find(f=>!f.indicators&&!f.measure&&!f.successCriteria);
 if(vagueForecast)out.push(rec('Success criteria','high',`Define measurable success for “${label(vagueForecast)}”`,'The forecast has no indicator or success criterion, so resolution could become subjective.',95,'Makes outcome resolution consistent and auditable.','forecast-criteria',[vagueForecast.id],'Improve'));
 const unverified=interventions.find(r=>['Complete','Completed','Implemented'].includes(r.status)&&!events.some(e=>e.interventionId===r.id&&/verif/i.test(String(e.type||e.eventType||e.title||''))));
 if(unverified)out.push(rec('Verification plan','high',`Verify “${label(unverified)}” with measured evidence`,'The intervention appears complete, but no verification event records whether it achieved the intended result.',96,'Prevents completion status from being mistaken for effectiveness.','verification',[unverified.id],'Learn'));
 else {const planned=interventions.find(r=>!['Complete','Completed','Implemented','Cancelled'].includes(r.status));if(planned&&!events.some(e=>e.interventionId===planned.id&&/verif|plan/i.test(String(e.type||e.eventType||e.title||''))))out.push(rec('Verification plan','medium',`Define verification before implementing “${label(planned)}”`,'Verification is more reliable when its measure, timing, and evidence source are specified before implementation.',87,'Reduces hindsight bias and ambiguous closeout.','verification',[planned.id],'Improve'))}
 const overdue=forecasts.find(f=>f.status!=='Resolved'&&f.targetDate&&new Date(f.targetDate).getTime()<today);
 if(overdue)out.push(rec('Outcome resolution','high',`Resolve the outcome for “${label(overdue)}”`,'The target date has passed. Leaving it unresolved weakens calibration analytics and lessons learned.',97,'Completes the prediction-feedback loop.','review',[overdue.id],'Learn'));
 const openHigh=frictions.filter(f=>Number(f.priority||0)>=50&&f.status!=='Resolved');
 const closeoutReasons=[];
 if(openHigh.length)closeoutReasons.push(`${openHigh.length} high-priority friction item${openHigh.length===1?' remains':'s remain'} open`);
 if(!reviews.length)closeoutReasons.push('no review records exist');
 if(!lessons.length)closeoutReasons.push('no reusable lesson has been captured');
 if(actions.some(a=>!['Done','Complete','Completed'].includes(a.status)&&a.dueDate&&new Date(a.dueDate).getTime()<today))closeoutReasons.push('overdue actions remain');
 if(closeoutReasons.length)out.push(rec('Closeout blocker','medium','Prepare the inquiry for defensible closeout',`Current blockers: ${closeoutReasons.join('; ')}.`,89,'Improves assurance, handoff, and future reuse.','closeout',[openHigh[0]?.id,reviews[0]?.id],'Learn'));
 return out.sort((a,b)=>(({high:3,medium:2,low:1}[b.priority])-({high:3,medium:2,low:1}[a.priority]))||(b.confidence-a.confidence));
}
function triggerHtml(i,ids){return ids.map(id=>{const f=recordById(i,id);return f?`<button class="copilot-trigger" onclick="inspectRecordV62('${esc(id)}',null,'${esc(i.id)}')">${esc(label(f.record))}</button>`:`<span class="copilot-trigger">Missing record</span>`}).join('')}
function actionLabel(a){return({'observation':'Create observation','evidence':'Create evidence','hypothesis':'Create hypothesis','assumption':'Create assumption','stakeholder':'Create stakeholder','perspective':'Create perspective','forecast-criteria':'Add success criteria','verification':'Create verification task','review':'Create review','closeout':'Create closeout action'})[a]||'Create record'}
function renderRecommendation(i,r,n){return `<article class="copilot-card ${r.priority}"><div class="eyebrow">${esc(r.kind)} · ${esc(r.priority)} priority</div><h4>${esc(r.title)}</h4><p>${esc(r.why)}</p><div class="copilot-rationale"><strong>Why Drift suggested this</strong><br>${esc(r.why)}</div>${r.triggerIds.length?`<div class="copilot-trigger-list">${triggerHtml(i,r.triggerIds)}</div>`:''}<div class="copilot-confidence"><span>Confidence</span><div class="bar"><span style="width:${r.confidence}%"></span></div><strong>${r.confidence}%</strong></div><div class="copilot-benefit">Potential benefit: ${esc(r.benefit)}</div><div class="toolbar" style="margin-top:12px"><button class="btn primary" onclick="applyCopilotRecommendationV71(${n})">${esc(actionLabel(r.action))}</button><button class="btn" onclick="createCopilotActionV71(${n})">Add to actions</button><button class="btn" onclick="dismissCopilotV71(${n})">Dismiss</button></div></article>`}
function ensureRel(i,fromId,toId,relation,notes){if(!fromId||!toId)return;i.relationships=i.relationships||[];if(!i.relationships.some(r=>r.fromId===fromId&&r.toId===toId&&r.relation===relation))i.relationships.push({id:uid(),fromId,toId,relation,notes,createdAt:now()})}
function addRecord(i,array,r){i[array]=i[array]||[];i[array].push(r);i.updatedAt=now();return r}
function makeRecord(i,r){const t=r.triggerIds[0], source=t?recordById(i,t):null, sourceLabel=source?label(source.record):'the inquiry';let created=null,type=null;
 if(r.action==='observation'){type='observe';created=addRecord(i,'observations',{id:uid(),title:r.title,notes:`Guided observation prompted by ${sourceLabel}. Record what is directly seen, measured, or heard.`,location:i.location||'',observedAt:new Date().toISOString().slice(0,10),createdAt:now(),updatedAt:now(),source:'Guided Copilot'});ensureRel(i,created.id,t,'responds to','Created from Guided Copilot recommendation.')}
 if(r.action==='evidence'){type='evidence';created=addRecord(i,'evidence',{id:uid(),title:`Evidence for ${sourceLabel}`,type:'Note',notes:'Add or attach the supporting evidence and describe its source, relevance, and limitations.',confidence:'50',createdAt:now(),updatedAt:now(),source:'Guided Copilot'});ensureRel(i,created.id,t,'supports','Evidence placeholder created by Guided Copilot.')}
 if(r.action==='hypothesis'){type='hypothesis';created=addRecord(i,'hypotheses',{id:uid(),title:r.title,hypothesis:`A candidate explanation for ${sourceLabel}.`,basis:`Triggered by ${sourceLabel}. Replace this prompt with the mechanism supported by current evidence.`,test:'State what observation or experiment would support, weaken, or falsify this explanation.',confidence:'50',status:'Proposed',createdAt:now(),updatedAt:now(),source:'Guided Copilot'});ensureRel(i,t,created.id,'explains','Candidate hypothesis prompted by Guided Copilot.')}
 if(r.action==='assumption'){type='assumption';created=addRecord(i,'assumptions',{id:uid(),title:`Assumption for ${sourceLabel}`,assumption:'State a condition that must remain true for this forecast to be valid.',forecastId:t||'',status:'Unknown',confidence:'50',notes:'Identify how and when this assumption will be tested.',createdAt:now(),updatedAt:now(),source:'Guided Copilot'});ensureRel(i,created.id,t,'supports','Assumption created for forecast review.')}
 if(r.action==='stakeholder'){type='stakeholder';created=addRecord(i,'stakeholders',{id:uid(),name:'New stakeholder group',role:'Describe their relationship to the inquiry.',influence:'Medium',impact:'Medium',engagement:'Not contacted',createdAt:now(),updatedAt:now(),source:'Guided Copilot'})}
 if(r.action==='perspective'){type='listen';created=addRecord(i,'perspectives',{id:uid(),participant:sourceLabel,perspective:'Record this stakeholder’s observation, interpretation, concern, need, or recommendation.',type:'Observation',confidence:'50',stakeholderId:t||'',createdAt:now(),updatedAt:now(),source:'Guided Copilot'});ensureRel(i,t,created.id,'responds to','Perspective requested by Guided Copilot.')}
 if(r.action==='forecast-criteria'){const f=source?.record;if(f){f.indicators=f.indicators||'Define a measurable indicator, baseline, target value, data source, and resolution date.';f.updatedAt=now();created=f;type='predict'}}
 if(r.action==='verification'){type='action';created=addRecord(i,'actions',{id:uid(),title:`Verification: ${sourceLabel}`,description:'Define the measure, baseline, target, evidence source, timing, and person responsible for verifying this intervention.',status:'Open',priority:'High',relatedInterventionId:t||'',createdAt:now(),updatedAt:now(),source:'Guided Copilot'});ensureRel(i,created.id,t,'tests','Verification action created by Guided Copilot.')}
 if(r.action==='review'){type='review';created=addRecord(i,'reviews',{id:uid(),title:`Outcome review: ${sourceLabel}`,outcome:'Record what actually happened.',comparison:'Compare expected and actual outcomes using the defined indicator.',lessons:'Explain what this result changes about the inquiry.',nextAction:'State the next decision or follow-up.',createdAt:now(),updatedAt:now(),source:'Guided Copilot'});ensureRel(i,t,created.id,'results in','Outcome review created by Guided Copilot.')}
 if(r.action==='closeout'){type='action';created=addRecord(i,'actions',{id:uid(),title:'Resolve inquiry closeout blockers',description:r.why,status:'Open',priority:'High',createdAt:now(),updatedAt:now(),source:'Guided Copilot'})}
 return{created,type};
}
window.renderCopilotV71=function(){
 const id=window.v71InquiryId||activeInquiries()[0]?.id||state.inquiries[0]?.id;window.v71InquiryId=id;const i=state.inquiries.find(x=>x.id===id);if(!i){copilotView.innerHTML='<div class="copilot-empty">Create an inquiry before using the Guided Copilot.</div>';return}
 const dismissed=new Set(state.copilotDismissed||[]),all=buildRecommendations(i),recs=all.filter(r=>!dismissed.has(i.id+'|'+r.title));window.v71Recommendations=recs;const stage=currentStage(i),filter=window.v71Filter||'All',visible=filter==='All'?recs:recs.filter(r=>r.stage===filter);
 copilotView.innerHTML=`<div class="copilot-hero"><div class="card"><div class="eyebrow">Guided inquiry support</div><h2>Guided Inquiry Copilot</h2><p>Drift recommends the next useful move from the structure of your records. Every recommendation explains its trigger, confidence, and potential benefit. Nothing is changed until you choose an action.</p><label>Inquiry<select onchange="window.v71InquiryId=this.value;renderCopilotV71()">${state.inquiries.map(x=>`<option value="${x.id}" ${x.id===i.id?'selected':''}>${esc(x.title)}</option>`).join('')}</select></label><div class="copilot-stage">${COPILOT_STAGES.map(x=>`<span class="${x===stage?'current':''}">${x}</span>`).join('')}</div></div><div class="card"><div class="eyebrow">Current guidance</div><div class="copilot-summary">${metric('Recommendations',recs.length)}${metric('High priority',recs.filter(x=>x.priority==='high').length)}${metric('Current stage',stage)}${metric('Triggered records',new Set(recs.flatMap(x=>x.triggerIds)).size)}</div></div></div><div class="section-head"><div><h3>Recommended next moves</h3><p class="status">Filtered recommendations remain deterministic, local, and explainable.</p></div><div class="copilot-filter">${['All',...COPILOT_STAGES].map(x=>`<button class="btn small ${filter===x?'active':''}" onclick="window.v71Filter='${x}';renderCopilotV71()">${x}</button>`).join('')}</div></div>${visible.length?`<div class="copilot-grid">${visible.map((r,n)=>renderRecommendation(i,r,recs.indexOf(r))).join('')}</div>`:'<div class="copilot-empty">No recommendations match this stage. The inquiry may already have sufficient coverage here.</div>'}`;
}
window.applyCopilotRecommendationV71=function(n){const i=state.inquiries.find(x=>x.id===window.v71InquiryId),r=(window.v71Recommendations||[])[n];if(!i||!r)return;const {created,type}=makeRecord(i,r);if(!created)return;state.copilotApplied=state.copilotApplied||[];state.copilotApplied.push({inquiryId:i.id,recommendation:r.title,recordId:created.id,date:now()});if(typeof audit==='function')audit('Copilot recommendation applied',r.title,i.id);saveState();renderCopilotV71();if(type&&typeof inspectRecordV62==='function')setTimeout(()=>inspectRecordV62(created.id,type,i.id),0)}
window.createCopilotActionV71=function(n){const i=state.inquiries.find(x=>x.id===window.v71InquiryId),r=(window.v71Recommendations||[])[n];if(!i||!r)return;const a=addRecord(i,'actions',{id:uid(),title:`Copilot: ${r.title}`,description:`Why suggested: ${r.why}\nPotential benefit: ${r.benefit}`,status:'Open',priority:r.priority==='high'?'High':r.priority==='medium'?'Medium':'Low',createdAt:now(),updatedAt:now(),source:'Guided Copilot'});r.triggerIds.forEach(id=>ensureRel(i,a.id,id,'responds to','Follow-up action created from Guided Copilot.'));saveState();renderCopilotV71();if(typeof inspectRecordV62==='function')setTimeout(()=>inspectRecordV62(a.id,'action',i.id),0)}
window.dismissCopilotV71=function(n){const i=state.inquiries.find(x=>x.id===window.v71InquiryId),r=(window.v71Recommendations||[])[n];if(!i||!r)return;state.copilotDismissed=state.copilotDismissed||[];const k=i.id+'|'+r.title;if(!state.copilotDismissed.includes(k))state.copilotDismissed.push(k);saveState();renderCopilotV71()}
const priorRender=window.render;
window.render=function(){if(currentView==='copilot'){document.querySelectorAll('.workspace').forEach(x=>x.classList.remove('active'));copilotView.classList.add('active');document.querySelectorAll('.nav button').forEach(b=>b.classList.toggle('active',b.dataset.view==='copilot'));viewTitle.textContent='Guided Copilot';renderCopilotV71();return}return priorRender()}
})();
