// Drift v7.4.0 Reasoning Quality
(function(){
const DIMS=[
 {id:'evidence',label:'Evidence sufficiency',weight:16},
 {id:'inference',label:'Inference support',weight:14},
 {id:'hypothesis',label:'Hypothesis testability',weight:14},
 {id:'alternatives',label:'Alternative explanations',weight:10},
 {id:'prediction',label:'Prediction specificity',weight:14},
 {id:'traceability',label:'Intervention traceability',weight:12},
 {id:'verification',label:'Verification completeness',weight:12},
 {id:'lesson',label:'Lesson transferability',weight:8}
];
function arr(i,k){return i[k]||[]}
function hasLink(i,from,to){return arr(i,'relationships').some(r=>(r.sourceId===from&&r.destinationId===to)||(r.fromId===from&&r.toId===to)||(r.source===from&&r.target===to))}
function textHasId(record,ids){const t=JSON.stringify(record||'');return ids.some(id=>id&&t.includes(id))}
function clamp(n){return Math.max(0,Math.min(100,Math.round(n)))}
function scoreEvidence(i){const ev=arr(i,'evidence'),obs=arr(i,'observations');let s=0;const reasons=[];if(ev.length){s+=35;reasons.push(`${ev.length} evidence record${ev.length===1?'':'s'} available.`)}else reasons.push('No evidence records exist.');if(obs.length){s+=20;reasons.push(`${obs.length} observation${obs.length===1?'':'s'} establish field context.`)}const linked=ev.filter(e=>arr(i,'relationships').some(r=>JSON.stringify(r).includes(e.id))||[...arr(i,'inferences'),...arr(i,'hypotheses'),...arr(i,'frictions')].some(x=>textHasId(x,[e.id]))).length;if(ev.length){s+=35*(linked/ev.length);reasons.push(`${linked} of ${ev.length} evidence records are explicitly connected to reasoning or diagnosis.`)}const rated=ev.filter(e=>e.confidence||e.reliability||e.relevance||e.quality).length;if(ev.length){s+=10*(rated/ev.length);reasons.push(`${rated} evidence records include quality or confidence metadata.`)}return {score:clamp(s),reasons}}
function scoreInference(i){const inf=arr(i,'inferences');if(!inf.length)return {score:0,reasons:['No inference records exist.']};const supported=inf.filter(x=>x.evidenceId||x.supportingEvidence||arr(i,'relationships').some(r=>JSON.stringify(r).includes(x.id)&&arr(i,'evidence').some(e=>JSON.stringify(r).includes(e.id)))).length;const alternatives=inf.filter(x=>x.alternatives||x.alternativeInterpretation).length;return {score:clamp(35+50*supported/inf.length+15*alternatives/inf.length),reasons:[`${supported} of ${inf.length} inferences identify supporting evidence.`,`${alternatives} inferences document alternative interpretations.`]}}
function scoreHypothesis(i){const h=arr(i,'hypotheses');if(!h.length)return {score:0,reasons:['No hypotheses exist.']};const testable=h.filter(x=>x.test||x.testMethod||x.falsification||x.disconfirmingEvidence||x.method).length;const supported=h.filter(x=>x.evidenceId||x.inferenceId||x.basis||arr(i,'relationships').some(r=>JSON.stringify(r).includes(x.id))).length;return {score:clamp(25+45*testable/h.length+30*supported/h.length),reasons:[`${testable} of ${h.length} hypotheses state how they could be tested or falsified.`,`${supported} hypotheses document a supporting basis or relationship.`]}}
function scoreAlternatives(i){const records=[...arr(i,'inferences'),...arr(i,'hypotheses'),...arr(i,'rootCauses')];if(!records.length)return {score:0,reasons:['No explanatory reasoning exists to assess alternatives.']};const n=records.filter(x=>x.alternatives||x.alternativeInterpretation||x.unknown||x.competingHypothesis||x.otherCauses).length;return {score:clamp(20+80*n/records.length),reasons:[`${n} of ${records.length} explanatory records explicitly preserve uncertainty or alternatives.`]}}
function scorePrediction(i){const f=arr(i,'forecasts');if(!f.length)return {score:0,reasons:['No forecasts exist.']};const measurable=f.filter(x=>x.targetDate&&(x.indicators||x.successCriteria||x.expectedValue||x.threshold)).length;const confidence=f.filter(x=>Number.isFinite(Number(x.confidence))).length;const assumptions=f.filter(x=>x.assumptions||arr(i,'assumptions').some(a=>textHasId(a,[x.id])||a.forecastId===x.id)).length;return {score:clamp(15+45*measurable/f.length+20*confidence/f.length+20*assumptions/f.length),reasons:[`${measurable} of ${f.length} forecasts are time-bound and measurable.`,`${confidence} include numeric confidence.`,`${assumptions} identify assumptions.`]}}
function scoreTrace(i){const ints=arr(i,'interventions');if(!ints.length)return {score:0,reasons:['No interventions exist.']};const linked=ints.filter(x=>x.frictionId||x.hypothesisId||x.forecastId||x.evidenceId||arr(i,'relationships').some(r=>JSON.stringify(r).includes(x.id))).length;const rationale=ints.filter(x=>x.rationale||x.why||x.description).length;return {score:clamp(20+55*linked/ints.length+25*rationale/ints.length),reasons:[`${linked} of ${ints.length} interventions trace to another record.`,`${rationale} include rationale or intended mechanism.`]}}
function scoreVerification(i){const ints=arr(i,'interventions');if(!ints.length)return {score:0,reasons:['No interventions exist to verify.']};const done=ints.filter(x=>/complete|implemented|done|verified/i.test(x.status||'')).length;const verified=ints.filter(x=>x.verification||x.verificationPlan||x.successMeasure||x.measuredResult||arr(i,'interventionEvents').some(e=>e.interventionId===x.id&&/verify|check|result/i.test(e.type||e.title||''))).length;return {score:clamp(15+35*done/ints.length+50*verified/ints.length),reasons:[`${done} interventions are marked implemented or complete.`,`${verified} contain a verification plan or measured result.`]}}
function scoreLesson(i){const l=arr(i,'lessons');if(!l.length)return {score:0,reasons:['No lessons exist.']};const scoped=l.filter(x=>x.scope||x.applicability||x.transferability).length;const supported=l.filter(x=>x.evidenceId||x.supportingRecordIds||x.sourceRecordId||arr(i,'relationships').some(r=>JSON.stringify(r).includes(x.id))).length;return {score:clamp(25+40*scoped/l.length+35*supported/l.length),reasons:[`${scoped} of ${l.length} lessons define where they apply.`,`${supported} lessons cite supporting records or relationships.`]}}
const SCORERS={evidence:scoreEvidence,inference:scoreInference,hypothesis:scoreHypothesis,alternatives:scoreAlternatives,prediction:scorePrediction,traceability:scoreTrace,verification:scoreVerification,lesson:scoreLesson};
function assess(i){const parts=DIMS.map(d=>({...d,...SCORERS[d.id](i)}));const total=clamp(parts.reduce((s,p)=>s+p.score*p.weight,0)/parts.reduce((s,p)=>s+p.weight,0));return {total,parts}}
function band(n){return n>=80?['Strong','strong']:n>=55?['Developing','developing']:['Needs work','weak']}
function nextAction(p){const map={evidence:['evidence','Add supporting evidence'],inference:['inference','Create supported inference'],hypothesis:['hypothesis','Create testable hypothesis'],alternatives:['hypothesis','Document alternative hypothesis'],prediction:['predict','Create measurable forecast'],traceability:['intervention','Create linked intervention'],verification:['action','Create verification action'],lesson:['lesson','Create transferable lesson']};return map[p.id]}
function qualityCard(p,i){const b=band(p.score),a=nextAction(p);return `<article class="quality-card"><div class="quality-score"><strong>${p.score}</strong><div><div class="quality-band ${b[1]}">${b[0]}</div><h4>${esc(p.label)}</h4></div></div><div class="bar"><span style="width:${p.score}%"></span></div><div class="quality-breakdown">${p.reasons.map(r=>`<div class="quality-reason">${esc(r)}</div>`).join('')}</div><div class="quality-actions"><button class="btn small" onclick="qualityCreateV73('${i.id}','${a[0]}','${esc(a[1])}')">${esc(a[1])}</button><button class="btn small" onclick="qualityFollowupV73('${i.id}','${p.id}','${esc(p.label)}')">Create follow-up</button></div></article>`}
function portfolio(){const rows=state.inquiries.map(i=>({i,a:assess(i)})).sort((a,b)=>a.a.total-b.a.total);const mean=rows.length?Math.round(rows.reduce((s,x)=>s+x.a.total,0)/rows.length):0;const strong=rows.filter(x=>x.a.total>=80).length,weak=rows.filter(x=>x.a.total<55).length;return {rows,mean,strong,weak}}
window.renderQualityV73=function(){const p=portfolio(),iid=window.qualityInquiryV73||activeInquiries()[0]?.id||state.inquiries[0]?.id,i=state.inquiries.find(x=>x.id===iid)||state.inquiries[0];window.qualityInquiryV73=i?.id;if(!i){qualityView.innerHTML='<div class="empty">Create or load an inquiry to assess reasoning quality.</div>';return}const a=assess(i),b=band(a.total);qualityView.innerHTML=`<div class="quality-hero"><div class="card"><div class="eyebrow">Explainable assurance</div><h2>Reasoning Quality</h2><p>Drift evaluates the structure and traceability of an inquiry. Scores reflect record completeness and explicit links, not whether a conclusion is true.</p><label>Inquiry<select onchange="window.qualityInquiryV73=this.value;renderQualityV73()">${state.inquiries.map(x=>`<option value="${x.id}" ${x.id===i.id?'selected':''}>${esc(x.title)}</option>`).join('')}</select></label><div class="quality-chain" style="margin-top:14px"><span>Evidence</span><b>→</b><span>Inference</span><b>→</b><span>Hypothesis</span><b>→</b><span>Prediction</span><b>→</b><span>Intervention</span><b>→</b><span>Verification</span><b>→</b><span>Lesson</span></div></div><div class="card"><div class="eyebrow">Overall quality</div><div class="quality-score"><strong>${a.total}</strong><div><div class="quality-band ${b[1]}">${b[0]}</div><div class="status">Weighted across eight dimensions</div></div></div><div class="bar"><span style="width:${a.total}%"></span></div><div class="quality-summary" style="margin-top:14px">${metric('Portfolio average',p.mean)}${metric('Strong inquiries',p.strong)}${metric('Needs work',p.weak)}${metric('Dimensions ≥80',a.parts.filter(x=>x.score>=80).length)}</div></div></div><div class="section-head"><div><h3>Quality breakdown</h3><p class="status">Every score shows what raised or lowered it and provides a direct next action.</p></div><button class="btn" onclick="qualitySnapshotV73('${i.id}')">Save assessment snapshot</button></div><div class="quality-grid">${a.parts.map(x=>qualityCard(x,i)).join('')}</div><div class="card" style="margin-top:18px"><div class="section-head" style="margin:0 0 10px"><div><h3>Portfolio comparison</h3><p class="status">Lowest-scoring inquiries appear first.</p></div></div><table class="quality-table"><thead><tr><th>Inquiry</th><th>Overall</th><th>Lowest dimension</th><th>Action</th></tr></thead><tbody>${p.rows.map(x=>{const low=[...x.a.parts].sort((a,b)=>a.score-b.score)[0];return `<tr><td><strong>${esc(x.i.title)}</strong></td><td>${x.a.total}</td><td>${esc(low.label)} (${low.score})</td><td><button class="btn small" onclick="window.qualityInquiryV73='${x.i.id}';renderQualityV73()">Review</button></td></tr>`}).join('')}</tbody></table></div>`}
window.qualityCreateV73=function(iid,type,title){currentInquiryId=iid;currentView='inquiry';render();if(typeof openRecordDialog==='function'){openRecordDialog(type);setTimeout(()=>{const input=recordFields.querySelector('[name="title"],[name="prediction"],[name="assumption"],[name="lesson"]');if(input&&!input.value)input.value=title},0)}}
window.qualityFollowupV73=function(iid,dim,label){const i=state.inquiries.find(x=>x.id===iid);if(!i)return;i.actions=i.actions||[];i.actions.push({id:uid(),title:`Improve reasoning quality: ${label}`,description:`Review the ${label.toLowerCase()} dimension and address the gaps identified by Drift v7.3.`,status:'Open',priority:'Medium',createdAt:now(),updatedAt:now(),source:'Reasoning Quality',qualityDimension:dim});saveState();if(typeof announceV65==='function')announceV65('Reasoning-quality follow-up created.');renderQualityV73()}
window.qualitySnapshotV73=function(iid){const i=state.inquiries.find(x=>x.id===iid);if(!i)return;i.qualityAssessments=i.qualityAssessments||[];const a=assess(i);i.qualityAssessments.push({id:uid(),createdAt:now(),version:APP_VERSION,total:a.total,parts:a.parts.map(x=>({id:x.id,label:x.label,score:x.score,reasons:x.reasons}))});saveState();if(typeof announceV65==='function')announceV65('Reasoning-quality snapshot saved.')}
window.DriftReasoningQualityV73={assess,portfolio};
const priorRender=window.render;
window.render=function(){if(currentView==='quality'){document.querySelectorAll('.workspace').forEach(x=>x.classList.remove('active'));qualityView.classList.add('active');document.querySelectorAll('.nav button').forEach(b=>b.classList.toggle('active',b.dataset.view==='quality'));viewTitle.textContent='Reasoning Quality';renderQualityV73();return}return priorRender()}
})();
