const WORKFLOW_V61={
 observe:{label:'Observe',subtitle:'Collect and compare what is happening.',tabs:[['observe','Observations'],['evidence','Evidence'],['stations','Stations'],['compare','Compare'],['changes','Changes']]},
 understand:{label:'Understand',subtitle:'Explain patterns, friction, causes, and perspectives.',tabs:[['diagnose','Friction'],['causes','Root Causes'],['reasoning','Reasoning'],['stakeholders','Stakeholders'],['guides','Interview Guides'],['listen','Perspectives'],['coding','Themes'],['consensus','Consensus'],['graph','Relationships']]},
 improve:{label:'Improve',subtitle:'Choose, test, and deliver deliberate changes.',tabs:[['interventions','Interventions'],['actions','Actions'],['backlog','Backlog'],['predict','Predictions'],['assumptions','Assumptions'],['experiments','Experiments']]},
 learn:{label:'Learn',subtitle:'Resolve outcomes, verify results, and close the loop.',tabs:[['calibration','Calibration'],['review','Reviews'],['verification','Verification'],['timeline','Timeline'],['governance','Governance']]}
};
let currentWorkflowStageV61='overview';
const legacyRenderInquiryTabV61=renderInquiryTab;
function tabStageV61(tab){for(const stage of Object.keys(WORKFLOW_V61)){if(WORKFLOW_V61[stage].tabs.some(x=>x[0]===tab))return stage}return 'overview'}
function setWorkflowStageV61(stage){currentWorkflowStageV61=stage;if(stage==='overview')currentTab='overview';else if(!WORKFLOW_V61[stage].tabs.some(x=>x[0]===currentTab))currentTab=WORKFLOW_V61[stage].tabs[0][0];renderInquiry()}
function setStageTabV61(tab){currentTab=tab;currentWorkflowStageV61=tabStageV61(tab);renderInquiry()}
function entityCountV61(i,tab){const map={observe:'observations',evidence:'evidence',stations:'stations',changes:'changes',diagnose:'frictions',causes:'rootCauses',interventions:'interventions',actions:'actions',stakeholders:'stakeholders',guides:'interviewGuides',listen:'perspectives',coding:'themes',predict:'forecasts',assumptions:'assumptions',experiments:'experiments',review:'reviews'};return map[tab]?(i[map[tab]]||[]).length:0}
function stageCompletionV61(i,stage){const excluded=['compare','graph','consensus','calibration','timeline','governance','verification','backlog','reasoning'];const tabs=WORKFLOW_V61[stage].tabs.filter(x=>!excluded.includes(x[0]));const populated=tabs.filter(x=>entityCountV61(i,x[0])>0).length;return tabs.length?Math.round(populated/tabs.length*100):0}
function stageNextStepV61(i,stage){if(stage==='observe'){if(!(i.observations||[]).length)return 'Record the first observation to establish what is happening.';if(!(i.evidence||[]).length)return 'Add supporting evidence to strengthen the observation record.';if((i.observations||[]).length<2)return 'Record a repeat observation so change can be compared.';return 'Compare observations and document meaningful change.'}if(stage==='understand'){if(!(i.frictions||[]).length)return 'Identify the primary friction or uncertainty revealed by observation.';if(!(i.rootCauses||[]).length)return 'Test likely causes with root-cause analysis.';if(!(i.perspectives||[]).length)return 'Gather an affected stakeholder perspective.';return 'Connect evidence, causes, and perspectives into a defensible explanation.'}if(stage==='improve'){if(!(i.interventions||[]).length)return 'Define an intervention that responds to a supported cause.';if(!(i.forecasts||[]).length)return 'Record the expected change before implementation.';if(!(i.actions||[]).length)return 'Break the intervention into owned actions.';return 'Run the intervention or experiment and preserve implementation history.'}if(stage==='learn'){if(!(i.reviews||[]).length)return 'Compare actual results with the baseline and expected outcome.';if(!(i.lessons||[]).length)return 'Capture a reusable lesson.';return 'Verify the result, resolve forecasts, and decide whether the inquiry is ready to close.'}return 'Frame the inquiry and choose the stage that needs attention.'}
function recentRecordsV61(i,stage){const keys={observe:['observations','evidence','changes'],understand:['frictions','rootCauses','perspectives','inferences','hypotheses'],improve:['interventions','actions','forecasts','experiments'],learn:['reviews','lessons','interventionEvents']}[stage]||[];return keys.flatMap(k=>(i[k]||[]).map(r=>r)).sort((a,b)=>String(b.updatedAt||b.createdAt||'').localeCompare(String(a.updatedAt||a.createdAt||''))).slice(0,5)}
function renderStageShellV61(i,stage){const cfg=WORKFLOW_V61[stage],score=stageCompletionV61(i,stage),recent=recentRecordsV61(i,stage),found=cfg.tabs.find(x=>x[0]===currentTab),subLabel=found?found[1]:'';const recentHtml=recent.length?'<div class="recent-strip">'+recent.map(r=>'<span class="recent-chip">'+esc(recordLabel(r))+'</span>').join('')+'</div>':'';const rail=cfg.tabs.map(x=>'<button class="'+(currentTab===x[0]?'active':'')+'" onclick="setStageTabV61(\''+x[0]+'\')">'+x[1]+'<span class="count">'+entityCountV61(i,x[0])+'</span></button>').join('');return '<div class="crumbs"><button onclick="setWorkflowStageV61(\'overview\')">'+esc(i.title)+'</button><span>›</span><strong>'+cfg.label+'</strong><span>›</span><span>'+esc(subLabel)+'</span></div><div class="stage-guidance"><div class="card"><div class="eyebrow">'+cfg.label+' stage</div><h3>'+cfg.subtitle+'</h3><div class="next-step"><strong>Recommended next step</strong><br>'+esc(stageNextStepV61(i,stage))+'</div></div><div class="card"><div class="eyebrow">Stage coverage</div><div class="stage-score">'+score+'%</div><div class="health"><span style="width:'+score+'%"></span></div><p class="status">Based on populated working records in this stage.</p></div></div>'+recentHtml+'<div class="stage-shell"><aside class="stage-rail"><div class="card">'+rail+'</div></aside><section>'+legacyRenderInquiryTabV61(currentTab,i)+'</section></div>'}
renderInquiry=function(){const i=getInquiry();if(!i){currentView='inquiries';return render()}if(currentTab!=='overview')currentWorkflowStageV61=tabStageV61(currentTab);const groups=[['overview','Overview','Frame and orient the inquiry.']].concat(Object.keys(WORKFLOW_V61).map(k=>[k,WORKFLOW_V61[k].label,WORKFLOW_V61[k].subtitle]));const groupHtml=groups.map(x=>'<button class="workflow-tab '+(currentWorkflowStageV61===x[0]?'active':'')+'" onclick="setWorkflowStageV61(\''+x[0]+'\')"><strong>'+x[1]+'</strong><small>'+x[2]+'</small></button>').join('');inquiryWorkspace.innerHTML='<div class="inquiry-header"><div><div class="eyebrow">'+esc(i.subject||'Inquiry')+'</div><h2>'+esc(i.title)+'</h2><p>'+esc(i.question)+'</p></div><div class="toolbar"><button class="btn" onclick="window.print()">Print / Save PDF</button><button class="btn" onclick="toggleArchive(\''+i.id+'\')">'+(i.archived?'Restore':'Archive')+'</button></div></div><div class="card" style="margin-bottom:14px"><div style="display:flex;justify-content:space-between"><strong>Inquiry health</strong><span>'+health(i)+'%</span></div><div class="health" style="margin-top:8px"><span style="width:'+health(i)+'%"></span></div></div><div class="workflow-tabs">'+groupHtml+'</div><div class="tab-panel active">'+(currentWorkflowStageV61==='overview'?renderOverview(i):renderStageShellV61(i,currentWorkflowStageV61))+'</div>'};
openInquiry=function(id){currentInquiryId=id;currentView='inquiry';currentTab='overview';currentWorkflowStageV61='overview';render()};
